import {
    FolderTreeItem,
    Library,
    LibraryState,
    LibraryType,
    MainPage,
    ProjectData,
    SchematicTool,
    TabType,
    WindowSection,
    GridStyle,
    TabData,
    SchematicTabData,
    Board2dTabData
} from "./types.slint";

export global Data {
    in property <bool> preview-mode: true;

    in property <string> window-title: "LibrePCB 1.2.0-unstable";

    in property <string> about-librepcb-details: "LibrePCB Version: 1.2.0\nGit Revision:     f079fa97b\nBuild Date:       2024-12-02T19:12:08\nQt Version:       6.2.4 (built against 6.2.4)\nCPU Architecture: x86_64\nOperating System: Ubuntu Core 22\nPlatform Plugin:  xcb\nTLS Library:      OpenSSL 3.0.2 15 Mar 2022\nOCC Library:      OCCT 7.7.2\nRuntime:          Snap";

    in property <string> hovered-status-tip;

    in property <string> workspace-path: "/path/to/workspace";

    in property <string> cursor-coordinates: "X: 123.456 Y: 123.456";

    in property <string> grid-interval: "2.54";

    in property <string> unit: "mm";

    in-out property <bool> ignore-placement-locks: true;

    in-out property <MainPage> current-page: MainPage.home;

    in property <[FolderTreeItem]> workspace-folder: [
        {
            icon: @image-url("../img/library.png"),
            name: "project-1",
            path: "/path/to",
            is-folder: true,
        },
        {
            level: 1,
            icon: @image-url("../img/library.png"),
            name: "project-2.lpp",
            path: "/path/to/project-2.lpp",
        },
    ];

    in property <[FolderTreeItem]> recent-projects: [
        {
            icon: @image-url("../img/library.png"),
            name: "project-1.lpp",
            path: "/path/to/project-1.lpp",
        },
        {
            icon: @image-url("../img/library.png"),
            name: "project-2.lpp",
            path: "/path/to/project-2.lpp",
        },
    ];

    in property <[FolderTreeItem]> favorite-projects: recent-projects;

    in property <[ProjectData]> projects: [
        {
            valid: true,
            path: "/path/to/project-1.lpp",
            name: "Project 1",
            schematics: ["Power", "Logic"],
            boards: ["Default", "Experiment"],
        },
        {
            valid: true,
            path: "/path/to/project-2.lpp",
            name: "Project 2",
            schematics: ["Power", "Logic"],
            boards: ["Default", "Experiment"],
        },
    ];

    in property <int> current-project-index: 0;

    in property <int> status-bar-progress: 50;

    in property <bool> refreshing-available-libraries: true;

    in property <int> outdated-libraries: 2;

    in property <int> checked-libraries: 3;

    in property <[Library]> libraries: [
        {
            name: "My Library",
            description: "My own local library.",
            version: "v1.0",
            icon: @image-url("../img/library.png"),
            type: LibraryType.local,
            state: LibraryState.unknown,
        },
        {
            name: "LibrePCB Base",
            description: "Official LibrePCB Base Library",
            version: "v1.2.3",
            icon: @image-url("../img/librepcb.png"),
            type: LibraryType.remote,
            state: LibraryState.up-to-date,
        },
        {
            name: "Microchip Technology / Atmel",
            description: "Integrated circuits and more (unofficial).",
            version: "v0.5",
            icon: @image-url("../img/microchip.png"),
            type: LibraryType.remote,
            state: LibraryState.outdated,
        },
        {
            name: "LibrePCB Integrated Circuits",
            description: "Official LibrePCB Integrated Circuits Library",
            icon: @image-url("../img/librepcb.png"),
            type: LibraryType.online,
        },
        {
            name: "Microchip Technology / Atmel",
            description: "Integrated circuits and more (unofficial).",
            icon: @image-url("../img/microchip.png"),
            type: LibraryType.online,
            progress: 42,
        },
    ];

    in property <[WindowSection]> sections: [
        {
            tabs: [
                {
                    type: TabType.create-library,
                    title: "Create Lib",
                    icon: @image-url("../img/plus.svg"),
                    project-index: -1,
                },
                {
                    type: TabType.download-library,
                    title: "Download Lib",
                    icon: @image-url("../img/download.svg"),
                    project-index: -1,
                },
                {
                    type: TabType.schematic,
                    title: "Schematic",
                    icon: @image-url("../img/image.svg"),
                    project-index: 0,
                },
                {
                    type: TabType.board-2d,
                    title: "Board",
                    icon: @image-url("../img/projects.png"),
                    project-index: 0,
                },
            ],
            create-library-tabs: [
                {
                    name: "My Library",
                    name-error: "Name error",
                    description: "",
                    author: "",
                    author-default: "Me",
                    version: "",
                    version-default: "0.1",
                    version-error: "Version error",
                    url: "",
                    url-error: "URL error",
                    cc0: false,
                    directory: "",
                    directory-default: "My_Library.lplib",
                    directory-error: "Directory error",
                    valid: true,
                    creation-error: "Creation error",
                },
            ],
            download-library-tabs: [
                { },
                {
                    url: "",
                    url-error: "URL error",
                    url-suggestion: "https://example.com/library.zip",
                    directory: "",
                    directory-default: "My_Library.lplib",
                    directory-error: "Directory error",
                    valid: true,
                    download-running: true,
                    download-progress: 42,
                    download-error: "Download error",
                },
            ],
            schematic-tabs: [
                { },
                { },
                {
                    background-color: Colors.white,
                    overlay-color: Colors.black,
                    grid-style: GridStyle.none,
                    show-pin-numbers: false,
                    active-tool: SchematicTool.draw-polygon,
                },
            ],
            board-2d-tabs: [
                { },
                { },
                { },
                {
                    background-color: Colors.black,
                    overlay-color: Colors.white,
                    grid-style: GridStyle.none,
                },
            ],
            current-tab-index: 2,
        },
        {
            tabs: [
                {
                    type: TabType.board-3d,
                    title: "3D",
                    icon: @image-url("../img/projects.png"),
                    project-index: 1,
                },
            ],
            board-2d-tabs: [
                {
                    background-color: Colors.white,
                    overlay-color: Colors.gray,
                    grid-style: GridStyle.none,
                },
            ],
            current-tab-index: 0,
        },
    ];

    in property <int> current-section-index: 0;

    // Auto-calculated data.
    in-out property <ProjectData> current-project: Data.projects[Data.current-project-index];
    in-out property <WindowSection> current-section: Data.sections[Data.current-section-index];
    in-out property <TabData> current-tab: current-section.tabs[current-section.current-tab-index];
    out property <bool> current-tab-is-2d: (Data.current-tab.type == TabType.schematic) || (Data.current-tab.type == TabType.board-2d);
    out property <bool> current-tab-is-2d-or-3d: (Data.current-tab.type == TabType.schematic) || (Data.current-tab.type == TabType.board-2d) || (Data.current-tab.type == TabType.board-3d);
    in-out property <SchematicTabData> current-schematic-tab: current-section.schematic-tabs[current-section.current-tab-index];
    in-out property <Board2dTabData> current-board-2d-tab: current-section.board-2d-tabs[current-section.current-tab-index];
    out property <GridStyle> current-grid-style: (current-tab.type == TabType.schematic) ? current-schematic-tab.grid-style : current-board-2d-tab.grid-style;

    public function set-current-grid-style(gs: GridStyle) {
        if (current-tab.type == TabType.schematic) {
            current-section.schematic-tabs[current-section.current-tab-index].grid-style = gs;
        } else {
            current-section.board-2d-tabs[current-section.current-tab-index].grid-style = gs;
        }
    }
}
