export enum MainPage {
    home,
    libraries,
    project,
    rule-check,
    order,
    search,
    help,
}

export enum ActionId {
    // General
    open-workspace-folder,
    open-workspace-settings,
    open-keyboard-shortcuts-reference,
    open-video-tutorials,
    open-user-manual,
    open-support,
    open-donate,
    open-website,
    open-source-code,
    copy-application-details-into-clipboard,
    rescan-workspace-libraries,
    save,
    undo,
    redo,
    print,
    export-pdf,
    run-quick-check,
    run-drc,
    quit,

    // Window
    window-new,
    window-close,

    // Project
    project-new,
    project-open,
    project-close,
    project-import-examples,
    project-import-eagle,
    project-open-output-jobs,

    // Library panel
    library-panel-ensure-populated,
    library-panel-install,

    // Window section
    section-split,
    section-close,
    section-ok,
    section-cancel,
    section-grid-interval-increase,
    section-grid-interval-decrease,

    // Create library tab
    create-library-tab-open,

    // Download library tab
    download-library-tab-open,

    // 2D board viewer tab
    board-2d-tab-open-3d,

    todo,
}

export enum LengthUnit {
    millimeters,
    micrometers,
    nanometers,
    inches,
    mils,
}

export enum GridStyle {
    none,
    dots,
    lines,
}

export enum NotificationType {
    tip,
    info,
    warning,
    critical,
    progress,
}

export struct NotificationData {
    // Data from backend:
    type: NotificationType,
    title: string,
    description: string,
    button-text: string, // Optional
    progress: int,  // [%]

    // Features:
    supports-dont-show-again: bool,

    // Status:
    unread: bool,
    displayed: bool,

    // Special function members:
    button-clicked: bool,  // If set by UI, backend shall handle it.
    dismissed: bool,  // If set by UI, backend shall delete notification.
    dont-show-again: bool,  // If set by UI, backend shall delete notification.
}

//export enum RuleCheckMessageSeverity {
//    hint,
//    warning,
//    error,
//}

export struct RuleCheckMessageData {
    severity: NotificationType,
    message: string,
    description: string,
    approved: bool,
    supports-autofix: bool,
    autofix-requested: bool,  // Flag set by UI, reset by backend.
}

export enum LibraryType {
    local,
    remote,
    online,
}

export enum LibraryState {
    unknown,
    up-to-date,
    outdated,
}

export struct LibraryData {
    id: string,
    name: string,
    description: string,
    version: string,
    icon: image,
    recommended: bool,
    type: LibraryType,
    state: LibraryState,
    progress: int, // [%], 0 if not installing
    checked: bool,
    filtered-out: bool,
}

export struct FolderTreeItemData {
    level: int, // 0 = top level items
    icon: image,
    name: string,
    path: string,
    has-children: bool,
    expanded: bool,
    supports-pinning: bool,
    pinned: bool,
}

export struct QuickAccessItemData {
    name: string,
    path: string,
    pinned: bool,
}

export struct ProjectData {
    valid: bool,
    path: string,
    name: string,
    schematics: [string],
    boards: [string],
}

export enum TabType {
    home,
    create-library,
    download-library,
    schematic,
    board-2d,
    board-3d,
}

export enum RuleCheckState {
    not-available,
    not-run-yet,
    running,
    outdated,
    up-to-date,
}

export struct TabData {
    // Meta
    type: TabType,
    title: string,
    icon: image,
    project-index: int,

    // Rule check
    rule-check-state: RuleCheckState,
    rule-check-messages: [RuleCheckMessageData],
    rule-check-execution-error: string,  // Empty if no error

    // Features
    can-save: bool,
    can-export-graphics: bool,
    can-undo: bool,
    undo-text: string,
    can-redo: bool,
    redo-text: string,
    can-cut-copy: bool,
    can-paste: bool,
    can-remove: bool,
    can-rotate: bool,
    can-mirror: bool,
}

export struct CreateLibraryTabData {
    name: string,
    name-error: string,
    description: string,
    author: string,
    author-default: string,
    version: string,
    version-default: string,
    version-error: string,
    url: string,
    url-error: string,
    cc0: bool,
    directory: string,
    directory-default: string,
    directory-error: string,
    valid: bool,
    creation-error: string,
}

export struct DownloadLibraryTabData {
    url: string,
    url-error: string,
    url-suggestion: string,
    directory: string,
    directory-default: string,
    directory-error: string,
    valid: bool,
    download-running: bool,
    download-progress: int,
    download-error: string,
}

export enum SchematicTool {
    select,
    draw-wire,
    add-netlabel,
    draw-polygon,
    add-text,
    add-component,
    measure,
}

export struct SchematicTabData {
    background-color: brush,
    overlay-color: brush,
    grid-style: GridStyle,
    grid-interval: string,
    unit: LengthUnit,
    show-pin-numbers: bool,
    active-tool: SchematicTool,
    cursor: MouseCursor,
}

export struct Board2dTabData {
    background-color: brush,
    overlay-color: brush,
    grid-style: GridStyle,
    grid-interval: string,
    unit: LengthUnit,
}

export struct Board3dTabData {
    background-color: brush,
    overlay-color: brush,
}

export struct WindowSectionData {
    tabs: [TabData], // Tabs in this section
    create-library-tabs: [CreateLibraryTabData],
    download-library-tabs: [DownloadLibraryTabData],
    schematic-tabs: [SchematicTabData],
    board-2d-tabs: [Board2dTabData],
    board-3d-tabs: [Board3dTabData],
    current-tab-index: int,  // Currently opened tab in this section
    highlight: bool,
    frame: int, // Frame index to trigger repainting
}

export struct EditParseResult {
    valid: bool,
    evaluated-value: string,
    evaluated-unit: string,
}
