import { WindowSectionData, Board2dTabData } from "../../api/types.slint";
import { LengthEdit } from "../../common/lengthedit.slint";
import { Data } from "../../api/data.slint";

export component AddHoleToolBar inherits HorizontalLayout {
    in property <int> section-index;
    in-out property <WindowSectionData> section;
    property <[Board2dTabData]> tabs: section.board-2d-tabs;

    spacing: 5px;
    height: 25px;

    Text {
        vertical-alignment: center;
        text: @tr("Diameter:");
    }

    LengthEdit {
        value: tabs[section.current-tab-index].tool-drill.value;
        unit: tabs[section.current-tab-index].tool-drill.unit;
        can-decrease: tabs[section.current-tab-index].tool-drill.can-decrease;

        value-entered(v) => {
            tabs[section.current-tab-index].tool-drill.value = v;
        }

        unit-entered(u) => {
            tabs[section.current-tab-index].tool-drill.unit = u;
        }

        increase-triggered => {
            tabs[section.current-tab-index].tool-drill.increase = true;
        }

        decrease-triggered => {
            tabs[section.current-tab-index].tool-drill.decrease = true;
        }
    }
}
