import {
    ComboBox,
    LengthEdit,
} from "../../widgets.slint";
import {
    Board2dTabData,
    WindowSectionData,
} from "../../api.slint";

export component AddViaToolBar inherits HorizontalLayout {
    in property <int> section-index;
    in-out property <WindowSectionData> section;
    property <[Board2dTabData]> tabs: section.board-2d-tabs;

    spacing: 2px;

    net-cbx := ComboBox {
        model: tabs[section.current-tab-index].tool-net.items;
        current-index: tabs[section.current-tab-index].tool-net.current-index;

        current-index-changed(index) => {
            tabs[section.current-tab-index].tool-net.current-index = index;
        }
    }

    via-size-edt := LengthEdit {
        data: tabs[section.current-tab-index].tool-size;
        icon: @image-url("../../../../../bootstrap-icons/icons/record-circle-fill.svg");
        tooltip: @tr("Via Outer Diameter");
        min-width-text: "1.234";

        value-changed(v) => {
            tabs[section.current-tab-index].tool-size.value = v;
        }

        unit-changed(u) => {
            tabs[section.current-tab-index].tool-size.unit = u;
        }

        increase-triggered => {
            tabs[section.current-tab-index].tool-size.increase = true;
        }

        decrease-triggered => {
            tabs[section.current-tab-index].tool-size.decrease = true;
        }
    }

    via-drill-edt := LengthEdit {
        data: tabs[section.current-tab-index].tool-drill;
        icon: @image-url("../../../../../font-awesome/svgs/solid/bore-hole.svg");
        tooltip: @tr("Via Drill Diameter");
        min-width-text: "1.234";

        value-changed(v) => {
            tabs[section.current-tab-index].tool-drill.value = v;
        }

        unit-changed(u) => {
            tabs[section.current-tab-index].tool-drill.unit = u;
        }

        increase-triggered => {
            tabs[section.current-tab-index].tool-drill.increase = true;
        }

        decrease-triggered => {
            tabs[section.current-tab-index].tool-drill.decrease = true;
        }
    }
}
