import { ComboBox, Switch } from "std-widgets.slint";
import { WindowSectionData, Board2dTabData } from "../../api/types.slint";
import { LengthEdit } from "../../widgets.slint";
import { Data } from "../../api/data.slint";

export component AddViaToolBar inherits HorizontalLayout {
    in property <int> section-index;
    in-out property <WindowSectionData> section;
    property <[Board2dTabData]> tabs: section.board-2d-tabs;

    spacing: 5px;
    height: 25px;

    Text {
        vertical-alignment: center;
        text: @tr("Size:");
    }

    LengthEdit {
        value: tabs[section.current-tab-index].tool-size.value;
        unit: tabs[section.current-tab-index].tool-size.unit;
        can-decrease: tabs[section.current-tab-index].tool-size.can-decrease;

        value-entered(v) => {
            tabs[section.current-tab-index].tool-size.value = v;
        }

        unit-entered(u) => {
            tabs[section.current-tab-index].tool-size.unit = u;
        }

        increase-triggered => {
            tabs[section.current-tab-index].tool-size.increase = true;
        }

        decrease-triggered => {
            tabs[section.current-tab-index].tool-size.decrease = true;
        }
    }

    Text {
        vertical-alignment: center;
        text: @tr("Drill:");
    }

    LengthEdit {
        value: tabs[section.current-tab-index].tool-drill.value;
        unit: tabs[section.current-tab-index].tool-drill.unit;
        can-decrease: tabs[section.current-tab-index].tool-drill.can-decrease;

        value-entered(v) => {
            tabs[section.current-tab-index].tool-drill.value = v;
        }

        unit-entered(u) => {
            tabs[section.current-tab-index].tool-drill.unit = u;
        }

        increase-triggered => {
            tabs[section.current-tab-index].tool-drill.increase = true;
        }

        decrease-triggered => {
            tabs[section.current-tab-index].tool-drill.decrease = true;
        }
    }

    Text {
        vertical-alignment: center;
        text: @tr("Net:");
    }

    ComboBox {
        model: tabs[section.current-tab-index].tool-net.items;
        current-index: tabs[section.current-tab-index].tool-net.current-index;

        changed current-index => {
            if (tabs[section.current-tab-index].tool-net.current-index != self.current-index) {
                tabs[section.current-tab-index].tool-net.current-index = self.current-index;
            }
        }
    }
}
