import { ComboBox, Switch } from "std-widgets.slint";
import { WireMode, WindowSectionData, Board2dTabData } from "../../api/types.slint";
import { LengthEdit } from "../../common/lengthedit.slint";
import { Data } from "../../api/data.slint";

component WireModeButton inherits Rectangle {
    in property <image> icon;
    in property <bool> checked: false;

    callback clicked <=> ta.clicked;

    width: self.height;
    background: checked ? #202020 : (ta.has-hover ? #707070 : transparent);

    ta := TouchArea {
        Image {
            width: 100%;
            height: 100%;
            source: icon;
        }
    }
}

export component DrawTraceToolBar inherits HorizontalLayout {
    in property <int> section-index;
    in-out property <WindowSectionData> section;
    property <[Board2dTabData]> tabs: section.board-2d-tabs;

    spacing: 5px;
    height: 25px;

    WireModeButton {
        icon: @image-url("../../../../../../img/command_toolbars/wire_h_v.png");
        checked: tabs[section.current-tab-index].tool-wire-mode == WireMode.h-v;

        clicked => {
            tabs[section.current-tab-index].tool-wire-mode = WireMode.h-v;
        }
    }

    WireModeButton {
        icon: @image-url("../../../../../../img/command_toolbars/wire_v_h.png");
        checked: tabs[section.current-tab-index].tool-wire-mode == WireMode.v-h;

        clicked => {
            tabs[section.current-tab-index].tool-wire-mode = WireMode.v-h;
        }
    }

    WireModeButton {
        icon: @image-url("../../../../../../img/command_toolbars/wire_90_45.png");
        checked: tabs[section.current-tab-index].tool-wire-mode == WireMode.deg90-45;

        clicked => {
            tabs[section.current-tab-index].tool-wire-mode = WireMode.deg90-45;
        }
    }

    WireModeButton {
        icon: @image-url("../../../../../../img/command_toolbars/wire_45_90.png");
        checked: tabs[section.current-tab-index].tool-wire-mode == WireMode.deg45-90;

        clicked => {
            tabs[section.current-tab-index].tool-wire-mode = WireMode.deg45-90;
        }
    }

    WireModeButton {
        icon: @image-url("../../../../../../img/command_toolbars/wire_straight.png");
        checked: tabs[section.current-tab-index].tool-wire-mode == WireMode.straight;

        clicked => {
            tabs[section.current-tab-index].tool-wire-mode = WireMode.straight;
        }
    }

    Text {
        vertical-alignment: center;
        text: @tr("Width:");
    }

    LengthEdit {
        value: tabs[section.current-tab-index].tool-line-width.value;
        unit: tabs[section.current-tab-index].tool-line-width.unit;
        can-decrease: tabs[section.current-tab-index].tool-line-width.can-decrease;

        value-entered(v) => {
            tabs[section.current-tab-index].tool-line-width.value = v;
        }

        unit-entered(u) => {
            tabs[section.current-tab-index].tool-line-width.unit = u;
        }

        increase-triggered => {
            tabs[section.current-tab-index].tool-line-width.increase = true;
        }

        decrease-triggered => {
            tabs[section.current-tab-index].tool-line-width.decrease = true;
        }
    }

    Text {
        vertical-alignment: center;
        text: @tr("Auto:");
    }

    Switch {
        checked: tabs[section.current-tab-index].tool-filled;

        toggled => {
            tabs[section.current-tab-index].tool-filled = self.checked;
        }
    }

    Text {
        vertical-alignment: center;
        text: @tr("Layer:");
    }

    ComboBox {
        model: tabs[section.current-tab-index].tool-layer.items;
        current-index: tabs[section.current-tab-index].tool-layer.current-index;

        changed current-index => {
            if (tabs[section.current-tab-index].tool-layer.current-index != self.current-index) {
                tabs[section.current-tab-index].tool-layer.current-index = self.current-index;
            }
        }
    }

    Text {
        vertical-alignment: center;
        text: @tr("Via Size:");
    }

    LengthEdit {
        value: tabs[section.current-tab-index].tool-size.value;
        unit: tabs[section.current-tab-index].tool-size.unit;
        can-decrease: tabs[section.current-tab-index].tool-size.can-decrease;

        value-entered(v) => {
            tabs[section.current-tab-index].tool-size.value = v;
        }

        unit-entered(u) => {
            tabs[section.current-tab-index].tool-size.unit = u;
        }

        increase-triggered => {
            tabs[section.current-tab-index].tool-size.increase = true;
        }

        decrease-triggered => {
            tabs[section.current-tab-index].tool-size.decrease = true;
        }
    }

    Text {
        vertical-alignment: center;
        text: @tr("Via Drill:");
    }

    LengthEdit {
        value: tabs[section.current-tab-index].tool-drill.value;
        unit: tabs[section.current-tab-index].tool-drill.unit;
        can-decrease: tabs[section.current-tab-index].tool-drill.can-decrease;

        value-entered(v) => {
            tabs[section.current-tab-index].tool-drill.value = v;
        }

        unit-entered(u) => {
            tabs[section.current-tab-index].tool-drill.unit = u;
        }

        increase-triggered => {
            tabs[section.current-tab-index].tool-drill.increase = true;
        }

        decrease-triggered => {
            tabs[section.current-tab-index].tool-drill.decrease = true;
        }
    }
}
