import { ComboBox } from "std-widgets.slint";
import { WindowSectionData, Board2dTabData } from "../../api/types.slint";
import { Data } from "../../api/data.slint";

export component DrawPlaneToolBar inherits HorizontalLayout {
    in property <int> section-index;
    in-out property <WindowSectionData> section;
    property <[Board2dTabData]> tabs: section.board-2d-tabs;

    spacing: 5px;
    height: 25px;

    Text {
        vertical-alignment: center;
        text: @tr("Net:");
    }

    ComboBox {
        model: tabs[section.current-tab-index].tool-net.items;
        current-index: tabs[section.current-tab-index].tool-net.current-index;

        changed current-index => {
            if (tabs[section.current-tab-index].tool-net.current-index != self.current-index) {
                tabs[section.current-tab-index].tool-net.current-index = self.current-index;
            }
        }
    }

    Text {
        vertical-alignment: center;
        text: @tr("Layer:");
    }

    ComboBox {
        model: tabs[section.current-tab-index].tool-layer.items;
        current-index: tabs[section.current-tab-index].tool-layer.current-index;

        changed current-index => {
            if (tabs[section.current-tab-index].tool-layer.current-index != self.current-index) {
                tabs[section.current-tab-index].tool-layer.current-index = self.current-index;
            }
        }
    }
}
