import {
    ComboBox,
    IconButton,
    LengthEdit,
} from "../../widgets.slint";
import {
    Board2dTabData,
    WindowSectionData,
} from "../../api.slint";

export component DrawPolygonToolBar inherits HorizontalLayout {
    in property <int> section-index;
    in-out property <WindowSectionData> section;
    property <[Board2dTabData]> tabs: section.board-2d-tabs;

    spacing: 2px;

    layer-cbx := ComboBox {
        model: tabs[section.current-tab-index].tool-layer.items;
        current-index: tabs[section.current-tab-index].tool-layer.current-index;

        current-index-changed(index) => {
            tabs[section.current-tab-index].tool-layer.current-index = index;
        }
    }

    line-width-edt := LengthEdit {
        data: tabs[section.current-tab-index].tool-line-width;
        icon: @image-url("../../../../../bootstrap-icons/icons/border-width.svg");
        tooltip: @tr("Line Width");
        min-width-text: "1.234";

        value-changed(v) => {
            tabs[section.current-tab-index].tool-line-width.value = v;
        }

        unit-changed(u) => {
            tabs[section.current-tab-index].tool-line-width.unit = u;
        }

        increase-triggered => {
            tabs[section.current-tab-index].tool-line-width.increase = true;
        }

        decrease-triggered => {
            tabs[section.current-tab-index].tool-line-width.decrease = true;
        }
    }

    fill-sw := IconButton {
        icon: @image-url("../../../../../font-awesome/svgs/solid/fill-drip.svg");
        icon-scale: 0.6;
        tooltip: @tr("Fill Area");
        background-color: #202020;
        background-color-hovered: #404040;
        background-color-checked: black;
        color-enabled: #606060;
        color-hovered: #e0e0e0;
        color-checked: #e0e0e0;
        border-radius: 10px;
        checked: tabs[section.current-tab-index].tool-filled;

        clicked => {
            tabs[section.current-tab-index].tool-filled = !self.checked;
        }
    }
}
