// WARNING: This file is autogenerated by cbindgen, don't modify it manually.
// clang-format off

#pragma once

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
#include <QtCore>
#define NONNULL

namespace librepcb {
namespace rs {

extern "C" {

extern size_t ffi_qbytearray_len(const QByteArray * NONNULL obj);

extern const uint8_t *ffi_qbytearray_data(const QByteArray * NONNULL obj);

extern uint8_t *ffi_qbytearray_data_mut(QByteArray * NONNULL obj);

extern void ffi_qbytearray_resize(QByteArray * NONNULL obj,
                                  size_t len,
                                  uint8_t value);

extern size_t ffi_qstring_len(const QString * NONNULL obj);

extern const uint16_t *ffi_qstring_utf16(const QString * NONNULL obj);

extern void ffi_qstring_set(QString * NONNULL obj, const char *s, size_t len);

}  // extern "C"

}  // namespace rs
}  // namespace librepcb

// clang-format on
