import { Button, ProgressIndicator, StandardButton, Palette, VerticalBox } from "std-widgets.slint";
import { SideBar } from "./sidebar.slint";
import { LengthEdit } from "./common/lengthedit.slint";
import { LibrariesPanel } from "./library/librariespanel.slint";
import { ProjectPanel } from "./project/projectpanel.slint";
import { HomePanel } from "./homepanel.slint";
import { MenuBar } from "./menubar.slint";
import { WindowSection } from "./windowsection.slint";
import { MainPage, GridStyle } from "./api/types.slint";
import { Backend } from "./api/backend.slint";
import { Data } from "./api/data.slint";
import { HelpPanel } from "./helppanel.slint";
import { OrderPanel } from "./project/orderpanel.slint";

export { Backend, Data }

export component AppWindow inherits Window {
    property <length> panel-width: (self.width <= 800px) ? 250px : 350px;

    title: Data.window-title;
    background: #2a2a2a;
    icon: @image-url("img/librepcb.png");
    preferred-width: 1024px;
    preferred-height: 768px;

    public function focus-search() {
        menubar.focus-search();
    }

    forward-focus: fs;
    fs := FocusScope {
        key-pressed(event) => {
            return Backend.key-pressed(event);
        }
    }

    menubar := MenuBar {
        x: 0;
        y: 0;
        width: 100%;
        height: 26px;
        sections-start-x: sidebar.width + panel-width;
    }

    sidebar := SideBar {
        x: 0px;
        y: menubar.height;
        z: 100;
        width: (root.width <= 800px) ? 40px : 50px;
        height: parent.height - self.y - statusbar.height - 1px;
    }

    if Data.current-page == MainPage.home: HomePanel {
        x: sidebar.width;
        y: sidebar.y;
        width: panel-width;
        height: sidebar.height;
    }

    if Data.current-page == MainPage.libraries: LibrariesPanel {
        x: sidebar.width;
        y: sidebar.y;
        z: 90; // For the tooltips.
        width: panel-width;
        height: sidebar.height;
    }

    if Data.current-page == MainPage.project: ProjectPanel {
        x: sidebar.width;
        y: sidebar.y;
        width: panel-width;
        height: sidebar.height;
    }

    if Data.current-page == MainPage.order: OrderPanel {
        x: sidebar.width;
        y: sidebar.y;
        width: panel-width;
        height: sidebar.height;
    }

    if Data.current-page == MainPage.help: HelpPanel {
        x: sidebar.width;
        y: sidebar.y;
        z: 90; // For the tooltips.
        width: panel-width;
        height: sidebar.height;
    }

    HorizontalLayout {
        x: sidebar.width + panel-width;
        y: sidebar.y + 1px;
        width: parent.width - self.x;
        height: sidebar.height - 1px;

        Rectangle {
            background: #555555;
            width: 1px;
        }

        for section[i] in Data.sections: HorizontalLayout {
            WindowSection {
                section-index: i;
                section: section;
            }

            if i < (Data.sections.length - 1): Rectangle {
                width: 1px;
                horizontal-stretch: 0;
                background: #555555;
            }
        }
    }

    statusbar := Rectangle {
        x: 0;
        y: parent.height - self.height;
        width: parent.width;
        height: 25px;
        background: sidebar.background;

        HorizontalLayout {
            padding-left: 10px;
            padding-right: 10px;

            Text {
                horizontal-stretch: 1;
                text: Data.workspace-path;
            }

            Rectangle {
                width: 10px;
            }

            Text {
                vertical-alignment: center;
                font-family: "Noto Sans Mono";
                font-size: 11px;
                color: white;
                text: Data.cursor-coordinates;
            }

            Rectangle {
                width: 10px;
            }

            Rectangle {
                width: t-grid-interval.preferred-width + self.height - t-grid-interval.preferred-height;
                background: t-grid-interval.has-hover ? #505050 : #404040;

                t-grid-interval := TouchArea {
                    Text {
                        vertical-alignment: center;
                        font-family: "Noto Sans Mono";
                        font-size: 11px;
                        text: Data.grid-interval;
                    }

                    clicked => {
                        pw-grid-interval.show();
                    }
                }

                pw-grid-interval := PopupWindow {
                    x: -(self.preferred-width - parent.width) / 2;
                    y: -self.preferred-height;
                    close-policy: close-on-click-outside;

                    LengthEdit { }
                }
            }

            Rectangle {
                width: t-unit.preferred-width + self.height - t-unit.preferred-height;
                background: t-unit.has-hover ? #505050 : #404040;

                t-unit := TouchArea {
                    Text {
                        vertical-alignment: center;
                        font-size: 11px;
                        text: Data.unit;
                    }

                    clicked => {
                        pw-unit.show();
                    }
                }

                pw-unit := PopupWindow {
                    x: -(self.preferred-width - parent.width) / 2;
                    y: -self.preferred-height;

                    Rectangle {
                        background: #404040;

                        VerticalBox {
                            padding-left: 5px;
                            padding-right: 5px;

                            Text {
                                color: #cccccc;
                                text: "mm";
                            }

                            Text {
                                color: #cccccc;
                                text: "μm";
                            }

                            Text {
                                color: #cccccc;
                                text: "nm";
                            }

                            Text {
                                color: #cccccc;
                                text: "″";
                            }

                            Text {
                                color: #cccccc;
                                text: "mils";
                            }
                        }
                    }
                }
            }

            Rectangle {
                width: self.height;
                background: t-grid-style.has-hover ? #505050 : #404040;

                t-grid-style := TouchArea {
                    Image {
                        width: self.height * 0.7;
                        height: 100%;
                        image-fit: contain;
                        source: (Data.grid-style == GridStyle.lines) ? @image-url("img/grid-lines.svg") : ((Data.grid-style == GridStyle.dots) ? @image-url("img/grid-dots.svg") : @image-url("img/grid-none.svg"));
                        colorize: Palette.foreground;
                    }

                    clicked => {
                        if (Data.grid-style == GridStyle.none) {
                            Data.grid-style = GridStyle.dots;
                        } else if (Data.grid-style == GridStyle.dots) {
                            Data.grid-style = GridStyle.lines;
                        } else {
                            Data.grid-style = GridStyle.none;
                        }
                    }
                }
            }

            Rectangle {
                width: self.height;
                background: (!Data.locked) ? #900000 : (t-lock.has-hover ? #505050 : #404040);

                t-lock := TouchArea {
                    Image {
                        width: self.height * 0.7;
                        height: 100%;
                        image-fit: contain;
                        source: Data.locked ? @image-url("img/lock-closed.svg") : @image-url("img/lock-open.svg");
                        colorize: (!Data.locked) ? white : Palette.foreground;
                    }

                    clicked => {
                        Data.locked = !Data.locked;
                    }
                }
            }

            Rectangle {
                width: 10px;
            }

            Rectangle {
                max-width: 150px;

                ProgressIndicator {
                    width: 100%;
                    visible: self.progress > 0 && self.progress < 1;
                    progress: Data.status-bar-progress / 100;
                }
            }
        }
    }
}
