import { ActionId, EditParseResult } from "./types.slint";

export global Callbacks {
    // Some action has been triggered
    //
    // - Action ID
    // - Section index (pass -1 for things outside a window section)
    pure callback action-triggered(ActionId, int);

    pure callback parse-length-input(string, string) -> EditParseResult;

    // An item in a project tree view has been double-clicked.
    //
    // - File path (see FolderTreeItem::path)
    pure callback project-item-doubleclicked(string);

    // A schematic in the projects panel has been clicked.
    //
    // - Schematic index
    pure callback schematic-clicked(int);

    // A board in the projects panel has been clicked.
    //
    // - Board index
    pure callback board-clicked(int);

    // Requested to switch to a particular tab
    //
    // - Section index
    // - Tab index
    pure callback tab-clicked(int, int);

    // Requested to close a particular tab
    //
    // - Section index
    // - Tab index
    pure callback tab-close-clicked(int, int);

    // Open a library
    //
    // - Library ID (see Library::id)
    pure callback open-library(string);

    // Uninstall a library
    //
    // - Library ID (see Library::id)
    pure callback uninstall-library(string);

    // Toggle checked state of all libraries
    //
    // - Check state
    pure callback toggle-libraries-checked(bool);

    // Render a graphics scene image
    //
    // - Section index
    // - Scene width
    // - Scene height
    // - Frame number (to be ignored)
    pure callback render-scene(int, length, length, int) -> image;

    // Scene pointer event
    //
    // - Section index
    // - Cursor position X (relative to scene)
    // - Cursor position Y (relative to scene)
    // - Scene location within window
    // - Pointer event
    pure callback scene-pointer-event(int, length, length, Point, PointerEvent) -> EventResult;

    // Scene scrolled event
    //
    // - Section index
    // - Cursor position X (relative to scene)
    // - Cursor position Y (relative to scene)
    // - Scroll event
    pure callback scene-scrolled(int, length, length, PointerScrollEvent) -> EventResult;

    // Scene button "zoom to fit content" clicked
    //
    // - Section index
    // - Scene width
    // - Scene height
    pure callback scene-zoom-fit-clicked(int, length, length);

    // Scene button "zoom in" clicked
    //
    // - Section index
    // - Scene width
    // - Scene height
    pure callback scene-zoom-in-clicked(int, length, length);

    // Scene button "zoom out" clicked
    //
    // - Section index
    // - Scene width
    // - Scene height
    pure callback scene-zoom-out-clicked(int, length, length);

    // Generic callback to open an URL
    //
    // - URL
    pure callback open-url(string);
}
