import {
    FolderTreeItem,
    Library,
    LibraryState,
    LibraryType,
    MainPage,
    Project,
    ProjectData,
    SchematicTool,
    TabType,
    WindowSection
} from "./types.slint";

export global Data {
    in property <bool> preview-mode: true;

    in-out property <MainPage> current-page: MainPage.libraries;

    in property <[FolderTreeItem]> workspace-folder: [
        {
            icon: @image-url("img/library.png"),
            name: "project-1",
            path: "/path/to",
            is-folder: true,
        },
        {
            level: 1,
            icon: @image-url("img/library.png"),
            name: "project-2.lpp",
            path: "/path/to/project-2.lpp",
        },
    ];

    in property <[FolderTreeItem]> recent-projects: [
        {
            icon: @image-url("img/library.png"),
            name: "project-1.lpp",
            path: "/path/to/project-1.lpp",
        },
        {
            icon: @image-url("img/library.png"),
            name: "project-2.lpp",
            path: "/path/to/project-2.lpp",
        },
    ];

    in property <[FolderTreeItem]> favorite-projects: recent-projects;

    in property <[Project]> open-projects: [
        {
            path: "/path/to/project-1.lpp",
            name: "Project 1",
        },
        {
            path: "/path/to/project-2.lpp",
            name: "Project 2",
        },
    ];

    in property <ProjectData> current-project: {
        valid: true,
        name: "Project 1",
        schematics: ["Power", "Logic"],
        boards: ["Default", "Experiment"],
    };

    in property <int> status-bar-progress: 50;

    in property <bool> refreshing-available-libraries: true;

    in property <int> outdated-libraries: 2;

    in property <int> checked-libraries: 3;

    in property <[Library]> libraries: [
        {
            name: "My Library",
            description: "My own local library.",
            version: "v1.0",
            icon: @image-url("img/library.png"),
            type: LibraryType.local,
            state: LibraryState.unknown,
        },
        {
            name: "LibrePCB Base",
            description: "Official LibrePCB Base Library",
            version: "v1.2.3",
            icon: @image-url("img/librepcb.png"),
            type: LibraryType.remote,
            state: LibraryState.up-to-date,
        },
        {
            name: "Microchip Technology / Atmel",
            description: "Integrated circuits and more (unofficial).",
            version: "v0.5",
            icon: @image-url("img/microchip.png"),
            type: LibraryType.remote,
            state: LibraryState.outdated,
        },
        {
            name: "LibrePCB Integrated Circuits",
            description: "Official LibrePCB Integrated Circuits Library",
            icon: @image-url("img/librepcb.png"),
            type: LibraryType.online,
        },
        {
            name: "Microchip Technology / Atmel",
            description: "Integrated circuits and more (unofficial).",
            icon: @image-url("img/microchip.png"),
            type: LibraryType.online,
            progress: 42,
        },
    ];

    in property <[WindowSection]> sections: [
        {
            tabs: [
                {
                    type: TabType.create-library,
                    title: "Create Lib",
                },
                {
                    type: TabType.download-library,
                    title: "Download Lib",
                },
                {
                    type: TabType.schematic,
                    title: "Schematic",
                },
                {
                    type: TabType.board-2d,
                    title: "Board",
                },
            ],
            create-library-tabs: [
                {
                    name: "My Library",
                    name-error: "Name error",
                    description: "",
                    author: "",
                    author-default: "Me",
                    version: "",
                    version-default: "0.1",
                    version-error: "Version error",
                    url: "",
                    url-error: "URL error",
                    cc0: false,
                    directory: "",
                    directory-default: "My_Library.lplib",
                    directory-error: "Directory error",
                    valid: true,
                    creation-error: "Creation error",
                },
            ],
            download-library-tabs: [
                { },
                {
                    url: "",
                    url-error: "URL error",
                    url-suggestion: "https://example.com/library.zip",
                    directory: "",
                    directory-default: "My_Library.lplib",
                    directory-error: "Directory error",
                    valid: true,
                    download-running: true,
                    download-progress: 42,
                    download-error: "Download error",
                },
            ],
            schematic-tabs: [
                { },
                { },
                {
                    background-color: Colors.white,
                    overlay-color: Colors.black,
                    show-pin-numbers: false,
                    active-tool: SchematicTool.draw-polygon,
                },
            ],
            board-2d-tabs: [
                { },
                { },
                { },
                {
                    background-color: Colors.black,
                    overlay-color: Colors.white,
                },
            ],
            current-tab-index: 2,
        },
        {
            tabs: [
                {
                    type: TabType.board-3d,
                    title: "3D",
                },
            ],
            board-2d-tabs: [
                {
                    background-color: Colors.white,
                    overlay-color: Colors.gray,
                },
            ],
            current-tab-index: 0,
        },
    ];

    in property <int> current-section-index: 0;
}
