import { Globals } from "./globals.slint";

export component EmptyTab inherits Rectangle {
    in-out property <int> section-id;

    Text {
        width: 90%;
        color: gray;
        horizontal-alignment: center;
        vertical-alignment: center;
        font-size: 30px;
        wrap: word-wrap;
        text: @tr("Open a library, schematic or board.");
    }

    TouchArea {
        pointer-event(e) => {
            return Globals.scene-pointer-event(section-id, self.mouse-x, self.mouse-y, root.width, root.height, e);
        }
        scroll-event(e) => {
            return Globals.scene-scrolled(section-id, self.mouse-x, self.mouse-y, root.width, root.height, e);
        }
    }
}
