import { Globals } from "./globals.slint";

export component EmptyTab inherits Rectangle {
    in property <int> section-index;

    Text {
        width: 90%;
        color: gray;
        horizontal-alignment: center;
        vertical-alignment: center;
        font-size: 30px;
        wrap: word-wrap;
        text: @tr("Open a library, schematic or board.");
    }

    TouchArea {
        pointer-event(e) => {
            return Globals.scene-pointer-event(section-index, self.mouse-x, self.mouse-y, self.absolute-position, e);
        }

        scroll-event(e) => {
            return Globals.scene-scrolled(section-index, self.mouse-x, self.mouse-y, e);
        }
    }
}
