export enum MenuItemId {
    new-window,
}

export enum LibraryType {
    local,
    remote,
    online,
}

export enum LibraryState {
    unknown,
    up-to-date,
    outdated,
}

export struct Library {
    id: string,
    name: string,
    description: string,
    version: string,
    icon: image,
    type: LibraryType,
    state: LibraryState,
    progress: int, // [%], 0 if not installing
    checked: bool,
}

export struct EditParseResult {
    valid: bool,
    evaluated-value: string,
    evaluated-unit: string,
}

export global Globals {
    pure callback menu-item-triggered(MenuItemId);

    pure callback parse-length-input(string, string) -> EditParseResult;

    // Populate the installed-libraries and available-libraries models with data
    // if not done yet (lazy loading only if libraries are visible in the UI).
    pure callback ensure-libraries-populated();

    // Install all checked libraries
    pure callback install-checked-libraries();

    // Uninstall a library
    //
    // - Library ID (see Library::id)
    pure callback uninstall-library(string);

    in property <int> status-bar-progress: 50;

    in property <bool> refreshing-available-libraries: false;

    in property <int> installable-libraries: 3;

    in property <[Library]> libraries: [
        {
            name: "My Library",
            description: "My own local library.",
            version: "v1.0",
            icon: @image-url("img/library.png"),
            type: LibraryType.local,
            state: LibraryState.unknown,
        },
        {
            name: "LibrePCB Base",
            description: "Official LibrePCB Base Library",
            version: "v1.2.3",
            icon: @image-url("img/librepcb.png"),
            type: LibraryType.remote,
            state: LibraryState.up-to-date,
        },
        {
            name: "Microchip Technology / Atmel",
            description: "Integrated circuits and more (unofficial).",
            version: "v0.5",
            icon: @image-url("img/microchip.png"),
            type: LibraryType.remote,
            state: LibraryState.outdated,
        },
        {
            name: "LibrePCB Integrated Circuits",
            description: "Official LibrePCB Integrated Circuits Library",
            icon: @image-url("img/librepcb.png"),
            type: LibraryType.online,
        },
        {
            name: "Microchip Technology / Atmel",
            description: "Integrated circuits and more (unofficial).",
            icon: @image-url("img/microchip.png"),
            type: LibraryType.online,
            progress: 42,
        },
    ];
}
