export enum MenuItemId {
    new-window,
}

export enum LibraryType {
    local,
    remote,
    online,
}

export enum LibraryState {
    unknown,
    up-to-date,
    outdated,
}

export struct Library {
    id: string,
    name: string,
    description: string,
    version: string,
    icon: image,
    recommended: bool,
    type: LibraryType,
    state: LibraryState,
    progress: int, // [%], 0 if not installing
    checked: bool,
}

export struct FolderTreeItem {
    level: int,
    icon: image,
    name: string,
    path: string,
    is-folder: bool,
}

export struct Project {
    path: string,
    name: string,
}

export struct ProjectData {
    valid: bool,
    name: string,
}

export struct EditParseResult {
    valid: bool,
    evaluated-value: string,
    evaluated-unit: string,
}

export global Globals {
    pure callback menu-item-triggered(MenuItemId);

    // An item in a project tree view has been double-clicked.
    //
    // - File path (see FolderTreeItem::path)
    pure callback project-item-doubleclicked(string);

    pure callback parse-length-input(string, string) -> EditParseResult;

    // Populate the installed-libraries and available-libraries models with data
    // if not done yet (lazy loading only if libraries are visible in the UI).
    pure callback ensure-libraries-populated();

    // Install all checked libraries
    pure callback install-checked-libraries();

    // Uninstall a library
    //
    // - Library ID (see Library::id)
    pure callback uninstall-library(string);

    in property <[FolderTreeItem]> workspace-folder: [
        {
            icon: @image-url("img/library.png"),
            name: "project-1",
            path: "/path/to",
            is-folder: true,
        },
        {
            level: 1,
            icon: @image-url("img/library.png"),
            name: "project-2.lpp",
            path: "/path/to/project-2.lpp",
        },
    ];

    in property <[FolderTreeItem]> recent-projects: [
        {
            icon: @image-url("img/library.png"),
            name: "project-1.lpp",
            path: "/path/to/project-1.lpp",
        },
        {
            icon: @image-url("img/library.png"),
            name: "project-2.lpp",
            path: "/path/to/project-2.lpp",
        },
    ];

    in property <[FolderTreeItem]> favorite-projects: recent-projects;

    in property <[Project]> open-projects: [
        {
            path: "/path/to/project-1.lpp",
            name: "Project 1",
        },
        {
            path: "/path/to/project-2.lpp",
            name: "Project 2",
        },
    ];

    in property <ProjectData> current-project: {
        valid: true,
        name: "Project 1",
    };

    in property <int> status-bar-progress: 50;

    in property <bool> refreshing-available-libraries: false;

    in property <int> outdated-libraries: 2;

    in property <int> checked-libraries: 3;

    in property <[Library]> libraries: [
        {
            name: "My Library",
            description: "My own local library.",
            version: "v1.0",
            icon: @image-url("img/library.png"),
            type: LibraryType.local,
            state: LibraryState.unknown,
        },
        {
            name: "LibrePCB Base",
            description: "Official LibrePCB Base Library",
            version: "v1.2.3",
            icon: @image-url("img/librepcb.png"),
            type: LibraryType.remote,
            state: LibraryState.up-to-date,
        },
        {
            name: "Microchip Technology / Atmel",
            description: "Integrated circuits and more (unofficial).",
            version: "v0.5",
            icon: @image-url("img/microchip.png"),
            type: LibraryType.remote,
            state: LibraryState.outdated,
        },
        {
            name: "LibrePCB Integrated Circuits",
            description: "Official LibrePCB Integrated Circuits Library",
            icon: @image-url("img/librepcb.png"),
            type: LibraryType.online,
        },
        {
            name: "Microchip Technology / Atmel",
            description: "Integrated circuits and more (unofficial).",
            icon: @image-url("img/microchip.png"),
            type: LibraryType.online,
            progress: 42,
        },
    ];
}
