import { PanelHeader } from "./common/panelheader.slint";
import { Data } from "./api/data.slint";
import { Backend } from "./api/backend.slint";
import { Button, Palette } from "std-widgets.slint";
import { ToolTip } from "./common/tooltip.slint";

export component HelpPanel inherits Rectangle {
    background: #2a2a2a;

    VerticalLayout {
        HorizontalLayout {
            padding: 5px;
            spacing: 10px;

            Image {
                width: 35px;
                height: self.width;
                source: @image-url("../../../img/app/librepcb.svg");
            }

            Text {
                font-size: 23px;
                vertical-alignment: center;
                overflow: elide;
                text: Data.window-title;
            }
        }

        Rectangle {
            height: 1px;
            background: #555555;
        }

        VerticalLayout {
            padding: 5px;
            spacing: 10px;

            Text {
                wrap: word-wrap;
                text: @tr("LibrePCB is a free & open source schematic/layout-editor. It is mainly developed by Urban Bruhin, with the support of many other contributors.");
            }

            Text {
                wrap: word-wrap;
                font-italic: true;
                text: @tr("This is free software, released under the GNU General Public License (GPL) version 3 or later. You can find the full license text in our source code.");
            }
        }

        VerticalLayout {
            padding: 5px;
            spacing: 5px;

            Button {
                width: self.preferred-width;
                colorize-icon: true;
                icon: @image-url("img/webbrowser.svg");
                text: @tr("Website");
            }

            Button {
                width: self.preferred-width;
                colorize-icon: true;
                icon: @image-url("img/documentation.svg");
                text: @tr("User Manual & Tutorials");
            }

            Button {
                width: self.preferred-width;
                colorize-icon: true;
                icon: @image-url("img/github.svg");
                text: @tr("Source Code on GitHub");
            }

            Button {
                width: self.preferred-width;
                colorize-icon: true;
                icon: @image-url("img/keyboard-shortcuts.svg");
                text: @tr("Keyboard Shortcuts Reference");
            }
        }

        Rectangle { }

        PanelHeader {
            title: @tr("Details");

            Text {
                horizontal-stretch: 1;
                font-size: 11px;
                font-italic: true;
                vertical-alignment: center;
                overflow: elide;
                text: @tr("(please copy this into bug reports)");
            }

            Rectangle {
                width: parent.content-height;
                height: parent.content-height;
                background: ta-copy.has-hover ? #454545 : transparent;
                border-radius: 3px;

                ta-copy := TouchArea {
                    t-copy := Timer {
                        interval: 1s;
                        running: false;

                        triggered => {
                            i-copy.visible = true;
                            i-copy-check.visible = false;
                            self.running = false;
                        }
                    }

                    i-copy := Image {
                        y: parent.pressed ? 4px : 3px;
                        width: self.height;
                        height: parent.height - self.y * 2;
                        source: @image-url("img/copy.svg");
                        colorize: parent.has-hover ? white : Palette.foreground;
                    }

                    i-copy-check := Image {
                        y: 3px;
                        width: self.height;
                        height: parent.height - self.y * 2;
                        source: @image-url("img/check.svg");
                        colorize: lime;
                        visible: false;
                    }

                    if self.has-hover: ToolTip {
                        x: (parent.width / 2) - (self.width / 2);
                        y: parent.height + 5px;
                        text: i-copy-check.visible ? @tr("Copied!") : @tr("Copy to Clipboard");
                    }

                    clicked => {
                        i-copy.visible = false;
                        i-copy-check.visible = true;
                        t-copy.running = true;
                    }
                }
            }
        }

        VerticalLayout {
            padding: 5px;

            TextInput {
                font-family: "Noto Sans Mono";
                font-size: 11px;
                read-only: true;
                single-line: false;
                wrap: no-wrap;
                text: Data.about-librepcb-details;
            }
        }
    }
}
