import { HorizontalBox } from "std-widgets.slint";
export component LineEdit inherits Rectangle {
    in-out property <string> text <=> ti.text;
    in-out property <string> placeholder-text;
    property <string> validation-error: input-handler(self.text);

    pure callback input-handler(text: string) -> string;

    height: self.preferred-height;
    horizontal-stretch: 1;
    border-color: (validation-error != "") ? #ff0000 : (ti.has-focus ? #29d682 : #555555);
    border-width: 1px;
    border-radius: 10px;
    forward-focus: ti;

    HorizontalLayout {
        padding: 8px;
        padding-left: 10px;
        padding-right: 10px;

        ti := TextInput {
            font-size: 13px;
        }
    }

    if (text == "") && (placeholder-text != ""): Text {
        x: ti.x;
        y: 0;
        width: ti.width;
        height: root.height;
        color: #808080;
        font-size: 13px;
        vertical-alignment: center;
        overflow: elide;
        text: placeholder-text;
    }

    if validation-error != "": Text {
        x: ti.x + ti.width - self.width;
        y: 0;
        width: min(self.preferred-width, parent.width / 2);
        height: root.height;
        color: #ff0000;
        font-size: 10px;
        horizontal-alignment: right;
        vertical-alignment: center;
        wrap: word-wrap;
        overflow: elide;
        text: validation-error;
    }
}
