import { HorizontalBox } from "std-widgets.slint";
export component LineEdit inherits Rectangle {
    in-out property <string> text <=> ti.text;
    in-out property <string> placeholder-text;
    in-out property <string> validation-error;

    height: self.preferred-height;
    horizontal-stretch: 1;
    border-color: (validation-error != "") ? #ff0000 : (ti.has-focus ? #29d682 : #555555);
    border-width: 1px;
    border-radius: 10px;
    forward-focus: ti;

    ta := TouchArea {
        HorizontalLayout {
            padding: 8px;
            padding-left: 10px;
            padding-right: 10px;

            ti := TextInput {
                font-size: 13px;
            }
        }

        HorizontalLayout {
            padding-left: 10px;
            padding-right: 10px;
            x: 0;
            y: 0;
            width: root.width;
            height: root.height;

            if (text == "") && (placeholder-text != ""): Text {
                color: #808080;
                font-size: 13px;
                vertical-alignment: center;
                overflow: elide;
                text: placeholder-text;
            }

            Rectangle {
                horizontal-stretch: 1;

                if validation-error != "": Text {
                    x: ti.x + ti.preferred-width;
                    width: parent.width - self.x;
                    horizontal-alignment: right;
                    vertical-alignment: center;
                    font-size: 11px;
                    wrap: word-wrap;
                    overflow: elide;
                    color: #ff0000;
                    text: validation-error;
                }
            }

            if ta.has-hover && (ti.text != ""): Image {
                source: @image-url("img/close.svg");
                colorize: ta-clear.has-hover ? #ffffff : #b0b0b0;

                ta-clear := TouchArea {
                    clicked => {
                        ti.text = "";
                    }
                }
            }
        }
    }
}
