import { ActionId } from "./types.slint";
import { Data } from "./data.slint";
import { MenuItemData, Menu } from "./menu.slint";
import { Palette, LineEdit, TabWidget } from "std-widgets.slint";

struct MainMenuItemData {
    text: string,
    items: [MenuItemData],
}

component MainMenuItem inherits Rectangle {
    in property <string> text <=> t-title.text;
    in property <[MenuItemData]> items;

    width: t-title.preferred-width + 10px;
    background: ta.has-hover ? #505050 : #252525;

    t-title := Text {
        x: 5px;
        font-size: 14px;
    }

    ta := TouchArea {
        clicked => {
            menu.show();
        }
    }

    menu := Menu {
        x: 0;
        y: 22px;
        items: items;
    }
}

component MenuBarButton inherits TouchArea {
    in property icon <=> i.source;

    width: self.height;

    i := Image {
        width: root.pressed ? 90% : 100%;
        image-fit: contain;
        colorize: (!root.enabled) ? #606060 : (root.has-hover ? white : Palette.foreground);
    }
}

export component MenuBar inherits Rectangle {
    in property <length> sections-start-x;

    property <[MainMenuItemData]> items: [
        {
            text: @tr("File"),
            items: [
                {
                    id: ActionId.todo,
                    text: @tr("Save Project"),
                    handle-in-backend: true,
                },
                {
                    id: ActionId.window-new,
                    text: @tr("New Window"),
                    handle-in-backend: true,
                },
            ],
        },
        {
            text: @tr("Edit"),
            items: [
                {
                    id: ActionId.todo,
                    text: @tr("New Window"),
                    handle-in-backend: true,
                },
            ],
        },
        {
            text: @tr("View"),
            items: [
                {
                    id: ActionId.todo,
                    text: @tr("New Window"),
                    handle-in-backend: true,
                },
            ],
        },
        {
            text: @tr("Help"),
            items: [
                {
                    id: ActionId.todo,
                    text: @tr("New Window"),
                    handle-in-backend: true,
                },
            ],
        },
    ];

    background: #252525;

    public function focus-search() {
        le-search.focus();
    }

    HorizontalLayout {
        padding-right: 2px;

        for item in items: MainMenuItem {
            text: item.text;
            items: item.items;
        }

        Rectangle {
            width: 3px;
        }

        Rectangle {
            y: 4px;
            width: 1px;
            height: parent.height - 2 * self.y;
            background: #606060;
        }

        HorizontalLayout {
            padding-top: 5px;
            padding-bottom: 5px;
            padding-left: 8px;
            padding-right: 20px;
            spacing: 5px;

            MenuBarButton {
                enabled: Data.current-project.valid;
                icon: @image-url("img/save.svg");
            }

            MenuBarButton {
                enabled: Data.current-project.valid;
                icon: @image-url("img/pdf.svg");
            }

            MenuBarButton {
                enabled: Data.current-project.valid;
                icon: @image-url("img/print.svg");
            }

            MenuBarButton {
                enabled: Data.current-project.valid;
                icon: @image-url("img/undo.svg");
            }

            MenuBarButton {
                enabled: Data.current-project.valid;
                icon: @image-url("img/redo.svg");
            }
        }

        Rectangle {
            horizontal-stretch: 1;

            if Data.sections[Data.current-section-index].tabs.length > 0: HorizontalLayout {
                property <length> total-space: root.width - sections-start-x;
                property <length> section-width: total-space / Data.sections.length;
                property <length> offset: sections-start-x - parent.x - (self.width / 2);

                x: max(min(section-width * (0.5 + Data.current-section-index) + offset, parent.width - self.width - 10px), 0);
                width: self.preferred-width;
                padding-top: 5px;
                padding-bottom: 5px;
                spacing: 5px;

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/cut.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/copy.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/paste.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/delete.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/rotate-ccw.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/rotate-cw.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/mirror-horizontal.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/mirror-vertical.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/move.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/grid-dots.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/reset.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/lock-open.svg");
                }

                MenuBarButton {
                    enabled: Data.current-project.valid;
                    icon: @image-url("img/edit.svg");
                }
            }
        }

        le-search := LineEdit {
            y: 2px;
            height: parent.height - 2 * self.y;
            horizontal-stretch: 0;
            placeholder-text: @tr("Quick Find (Ctrl+F)");

            key-pressed(event) => {
                if (event.text == Key.Escape) {
                    self.clear-focus();
                    return accept;
                }
                return reject;
            }
        }
    }
}
