import { Globals, MenuItemId } from "./globals.slint";

struct MenuItemData {
    id: MenuItemId,
    text: string,
}

struct MainMenuItemData {
    text: string,
    items: [MenuItemData],
}

component MenuItem inherits Rectangle {
    in property <MenuItemId> id;
    in property <string> text <=> t-title.text;

    preferred-width: t-title.preferred-width + 20px;
    height: t-title.preferred-height + 10px;
    background: ta.has-hover ? #505050 : #353535;

    t-title := Text {
        x: 10px;
        width: 100%;
    }

    ta := TouchArea {
        clicked => {
            Globals.menu-item-triggered(id);
        }
    }
}

component Menu inherits PopupWindow {
    in property <[MenuItemData]> items;

    Rectangle {
        background: #353535;

        VerticalLayout {
            for item in items: MenuItem {
                text: item.text;
            }
        }
    }
}

component MainMenuItem inherits Rectangle {
    in property <string> text <=> t-title.text;
    in property <[MenuItemData]> items;

    width: t-title.preferred-width + 20px;
    background: ta.has-hover ? #505050 : #353535;

    t-title := Text {
        x: 10px;
        font-size: 13px;
    }

    ta := TouchArea {
        clicked => {
            menu.show();
        }
    }

    menu := Menu {
        x: 0;
        y: 22px;
        items: items;
    }
}

export component MenuBar inherits Rectangle {
    property <[MainMenuItemData]> items: [
        {
            text: "Window",
            items: [
                {
                    id: MenuItemId.new-window,
                    text: "New Window",
                },
            ],
        },
    ];

    x: 0;
    y: 0;
    height: 22px;
    background: #353535;

    HorizontalLayout {
        for item in items: MainMenuItem {
            text: item.text;
            items: item.items;
        }
    }
}
