import { ActionId } from "./types.slint";
import { MenuItemData, Menu } from "./menu.slint";

struct MainMenuItemData {
    text: string,
    items: [MenuItemData],
}

component MainMenuItem inherits Rectangle {
    in property <string> text <=> t-title.text;
    in property <[MenuItemData]> items;

    width: t-title.preferred-width + 10px;
    background: ta.has-hover ? #505050 : #252525;

    t-title := Text {
        x: 5px;
        font-size: 14px;
    }

    ta := TouchArea {
        clicked => {
            menu.show();
        }
    }

    menu := Menu {
        x: 0;
        y: 22px;
        items: items;
    }
}

export component MenuBar inherits Rectangle {
    property <[MainMenuItemData]> items: [
        {
            text: @tr("File"),
            items: [
                {
                    id: ActionId.todo,
                    text: @tr("Save Project"),
                    handle-in-backend: true,
                },
                {
                    id: ActionId.window-new,
                    text: @tr("New Window"),
                    handle-in-backend: true,
                },
            ],
        },
        {
            text: @tr("Edit"),
            items: [
                {
                    id: ActionId.todo,
                    text: @tr("New Window"),
                    handle-in-backend: true,
                },
            ],
        },
        {
            text: @tr("View"),
            items: [
                {
                    id: ActionId.todo,
                    text: @tr("New Window"),
                    handle-in-backend: true,
                },
            ],
        },
        {
            text: @tr("Help"),
            items: [
                {
                    id: ActionId.todo,
                    text: @tr("New Window"),
                    handle-in-backend: true,
                },
            ],
        },
    ];

    background: #353535;

    HorizontalLayout {
        for item in items: MainMenuItem {
            text: item.text;
            items: item.items;
        }

        Rectangle {
            width: 10px;
        }

        HorizontalLayout {
            padding-top: 5px;
            padding-bottom: 5px;
            spacing: 3px;

            TouchArea {
                width: 20px;

                Image {
                    width: parent.height;
                    image-fit: contain;
                    source: @image-url("img/save.svg");
                    colorize: parent.has-hover ? white : #d0d0d0;
                }
            }

            TouchArea {
                width: 20px;

                Image {
                    width: parent.height;
                    image-fit: contain;
                    source: @image-url("img/undo.svg");
                    colorize: parent.has-hover ? white : #d0d0d0;
                }
            }

            TouchArea {
                width: 20px;

                Image {
                    width: parent.height;
                    image-fit: contain;
                    source: @image-url("img/redo.svg");
                    colorize: parent.has-hover ? white : #d0d0d0;
                }
            }
        }
    }
}
