export component PanelHeader inherits Rectangle {
    in property <length> spacing-top <=> vl-root.padding-top;
    in property <string> title <=> t-title.text;
    out property <length> content-height: t-title.height;

    height: spacing-top + t-title.height + 1px;

    vl-root := VerticalLayout {
        padding-top: 5px;

        HorizontalLayout {
            padding-left: 5px;
            padding-right: 1px;
            spacing: 3px;

            t-title := Text {
                y: 2px;
                height: self.preferred-height + 4px;
                font-weight: 700;
            }

            @children
        }

        Rectangle {
            height: 1px;
            background: #555555;
        }
    }
}
