//import { ComboBox } from "std-widgets.slint";
import { Globals } from "./globals.slint";

export component ProjectsPanel inherits Rectangle {
    background: #2a2a2a;

    VerticalLayout {
        padding-top: 5px;

        Text {
            x: 5px;
            width: root.width;
            height: self.preferred-height;
            font-weight: 700;
            text: @tr("PROJECT:") + " " + Globals.current-project.name;
        }

        Rectangle {
            height: 1px;
            background: #555555;
        }
    }
}
