import { PanelHeader } from "./panelheader.slint";
import { Data } from "./data.slint";
import { Callbacks } from "./callbacks.slint";

component ProjectItem inherits Rectangle {
    in property <string> text <=> t-title.text;

    callback clicked <=> ta.clicked;

    background: ta.has-hover ? #404040 : transparent;

    HorizontalLayout {
        padding: 2px;
        padding-left: 12px;
        padding-right: 5px;

        t-title := Text { }
    }

    ta := TouchArea { }
}

export component ProjectPanel inherits Rectangle {
    background: #2a2a2a;

    VerticalLayout {
        alignment: LayoutAlignment.start;

        PanelHeader {
            title: Data.current-project.name;
        }

        PanelHeader {
            title: @tr("SCHEMATICS");
        }

        for schematic[index] in Data.current-project.schematics: ProjectItem {
            text: schematic;

            clicked => {
                Callbacks.schematic-clicked(index);
            }
        }

        PanelHeader {
            title: @tr("BOARDS");
        }

        for board[index] in Data.current-project.boards: ProjectItem {
            text: board;

            clicked => {
                Callbacks.board-clicked(index);
            }
        }
    }
}
