import { SideBarButton } from "./sidebarbutton.slint";
import { Globals } from "./globals.slint";

export enum MainPage {
    home,
    libraries,
    project,
    drc,
    search,
    help,
    preferences,
}

export component SideBar inherits Rectangle {
    in-out property <MainPage> page: MainPage.home;

    background: #353535;

    VerticalLayout {
        spacing: 0px;

        SideBarButton {
            icon: @image-url("img/home.svg");
            tooltip: "Home";
            checked: page == MainPage.home;
            clicked => {
                page = MainPage.home;
            }
        }

        SideBarButton {
            icon: @image-url("img/libraries.png");
            tooltip: "Libraries";
            status-background: #d4d400;
            status-color: black;
            status-text: (Globals.outdated-libraries > 0) ? Globals.outdated-libraries : "";
            checked: page == MainPage.libraries;
            clicked => {
                page = MainPage.libraries;
            }
        }

        SideBarButton {
            icon: @image-url("img/projects.png");
            tooltip: "Project";
            enabled: Globals.current-project.valid;
            checked: page == MainPage.project;
            clicked => {
                page = MainPage.project;
            }
        }

        SideBarButton {
            icon: @image-url("img/drc.svg");
            tooltip: "Design Rule Check";
            checked: page == MainPage.drc;
            enabled: Globals.current-project.valid;
            clicked => {
                page = MainPage.drc;
            }
        }

        SideBarButton {
            icon: @image-url("img/search.svg");
            tooltip: "Search";
            checked: page == MainPage.search;
            clicked => {
                page = MainPage.search;
            }
        }

        Rectangle {
            vertical-stretch: 1;
        }

        SideBarButton {
            icon: @image-url("img/help.svg");
            tooltip: "Help";
            checked: page == MainPage.help;
            clicked => {
                page = MainPage.help;
            }
        }

        SideBarButton {
            icon: @image-url("img/settings.svg");
            tooltip: "Preferences";
            checked: page == MainPage.preferences;
            clicked => {
                page = MainPage.preferences;
            }
        }
    }
}
