import { SideBarButton } from "./sidebarbutton.slint";
import { MainPage } from "./api/types.slint";
import { Data } from "./api/data.slint";
import { ActionId, ProjectData, RuleCheckState } from "./api/types.slint";
import { Backend } from "./api/backend.slint";

export component SideBar inherits Rectangle {
    property <ProjectData> project: Data.projects[Data.current-project-index];

    background: #353535;

    VerticalLayout {
        spacing: 0px;

        SideBarButton {
            icon: @image-url("img/home.svg");
            tooltip: @tr("Home");
            checked: Data.current-page == MainPage.home;

            clicked => {
                Data.current-page = MainPage.home;
            }
        }

        SideBarButton {
            icon: @image-url("img/libraries.png");
            tooltip: @tr("Libraries");
            status-background: #d4d400;
            status-color: black;
            status-text: {
                if Data.refreshing-available-libraries {
                    if (mod(animation-tick(), 1000ms) >= 666ms) {
                        return "...";
                    } else if (mod(animation-tick(), 1000ms) >= 333ms) {
                        return "..";
                    } else {
                        return ".";
                    }
                } else if Data.outdated-libraries > 0 {
                    return Data.outdated-libraries;
                } else {
                    return "";
                }
            };
            checked: Data.current-page == MainPage.libraries;

            clicked => {
                Data.current-page = MainPage.libraries;
            }
        }

        SideBarButton {
            icon: @image-url("img/files.svg");
            tooltip: @tr("Open Documents");
            enabled: project.valid;
            checked: Data.current-page == MainPage.project;

            clicked => {
                Data.current-page = MainPage.project;
            }
        }

        SideBarButton {
            property <RuleCheckState> state: Data.current-tab.rule-check-state;
            property <int> messages: Data.current-tab.rule-check-messages.length;
            property <string> title: Data.get-rule-check-title-for-tab-type(Data.current-tab.type);

            icon: @image-url("img/drc.svg");
            tooltip: title;
            status-background: {
                if (state == RuleCheckState.running) {
                    return #d4d400;
                } else if (state == RuleCheckState.up-to-date) {
                    return (messages == 0) ? #00ff00 : #ff0000;
                } else {
                    return #d4d4d4;
                }
            };
            status-color: {
                if ((state == RuleCheckState.up-to-date) && (messages != 0)) {
                    return white;
                } else {
                    return black;
                }
            };
            status-text: {
                if (state == RuleCheckState.running) {
                    if (mod(animation-tick(), 1000ms) >= 666ms) {
                        return "...";
                    } else if (mod(animation-tick(), 1000ms) >= 333ms) {
                        return "..";
                    } else {
                        return ".";
                    }
                } else if ((state == RuleCheckState.up-to-date) || (state == RuleCheckState.outdated)) {
                    return (messages == 0) ? "ok" : messages;
                } else {
                    return "";
                }
            };
            enabled: state != RuleCheckState.not-available;
            checked: Data.current-page == MainPage.rule-check;

            clicked => {
                Data.current-page = MainPage.rule-check;
            }
        }

        SideBarButton {
            icon: @image-url("img/output-jobs.svg");
            tooltip: @tr("Output Jobs");
            enabled: project.valid;

            clicked => {
                Backend.action-triggered(ActionId.project-open-output-jobs, Data.current-project-index);
            }
        }

        SideBarButton {
            icon: @image-url("img/shopping-cart.svg");
            tooltip: @tr("Order PCB");
            enabled: project.valid;
            checked: Data.current-page == MainPage.order;

            clicked => {
                Data.current-page = MainPage.order;
            }
        }

        SideBarButton {
            icon: @image-url("img/search.svg");
            tooltip: @tr("Search");
            checked: Data.current-page == MainPage.search;

            clicked => {
                Data.current-page = MainPage.search;
            }
        }

        Rectangle {
            vertical-stretch: 1;
        }

        SideBarButton {
            icon: @image-url("img/settings.svg");
            tooltip: @tr("Preferences");
            checked: false;

            clicked => {
                Backend.action-triggered(ActionId.open-workspace-settings, -1);
            }
        }

        SideBarButton {
            icon: @image-url("img/help.svg");
            tooltip: @tr("Help / About");
            checked: Data.current-page == MainPage.help;

            clicked => {
                Data.current-page = MainPage.help;
            }
        }
    }
}
