import { SideBarButton } from "./sidebarbutton.slint";
import { MainPage } from "./api/types.slint";
import { Data } from "./api/data.slint";
import { ActionId, ProjectData } from "./api/types.slint";
import { Backend } from "./api/backend.slint";

export component SideBar inherits Rectangle {
    property <ProjectData> project: Data.projects[Data.current-project-index];

    background: #353535;

    VerticalLayout {
        spacing: 0px;

        SideBarButton {
            icon: @image-url("img/home.svg");
            tooltip: "Home";
            checked: Data.current-page == MainPage.home;
            clicked => {
                Data.current-page = MainPage.home;
            }
        }

        SideBarButton {
            icon: @image-url("img/libraries.png");
            tooltip: "Libraries";
            status-background: #d4d400;
            status-color: black;
            status-text: (Data.outdated-libraries > 0) ? Data.outdated-libraries : "";
            checked: Data.current-page == MainPage.libraries;
            clicked => {
                Data.current-page = MainPage.libraries;
            }
        }

        SideBarButton {
            icon: @image-url("img/projects.png");
            tooltip: "Project";
            enabled: project.valid;
            checked: Data.current-page == MainPage.project;
            clicked => {
                Data.current-page = MainPage.project;
            }
        }

        SideBarButton {
            icon: @image-url("img/drc.svg");
            tooltip: "Design Rule Check";
            enabled: project.valid;
            checked: Data.current-page == MainPage.drc;
            clicked => {
                Data.current-page = MainPage.drc;
            }
        }

        SideBarButton {
            icon: @image-url("img/output-jobs.svg");
            tooltip: "Output Jobs";
            enabled: project.valid;
            checked: Data.current-page == MainPage.output-jobs;
            clicked => {
                Data.current-page = MainPage.output-jobs;
            }
        }

        SideBarButton {
            icon: @image-url("img/shopping-cart.svg");
            tooltip: "Order PCB";
            enabled: project.valid;
            checked: Data.current-page == MainPage.order;
            clicked => {
                Data.current-page = MainPage.order;
            }
        }

        SideBarButton {
            icon: @image-url("img/search.svg");
            tooltip: "Search";
            checked: Data.current-page == MainPage.search;
            clicked => {
                Data.current-page = MainPage.search;
            }
        }

        Rectangle {
            vertical-stretch: 1;
        }

        SideBarButton {
            icon: @image-url("img/settings.svg");
            tooltip: "Preferences";
            checked: false;
            clicked => {
                Backend.action-triggered(ActionId.open-workspace-settings, -1);
            }
        }

        SideBarButton {
            icon: @image-url("img/help.svg");
            tooltip: "Help";
            checked: Data.current-page == MainPage.help;
            clicked => {
                Data.current-page = MainPage.help;
            }
        }
    }
}
