import { Globals, Tab, TabType } from "./globals.slint";
export component WindowSection inherits Rectangle {
    in property <int> section;
    in property <[Tab]> tabs;
    in-out property <int> current-tab-index;
    in property <int> scene-frame;

    tabBar := Rectangle {
        x: 0;
        y: 0;
        height: 30px;
        background: #353535;

        HorizontalLayout {
            alignment: LayoutAlignment.start;

            for tab[index] in tabs: Rectangle {
                background: (index == current-tab-index) ? #505050 : (ta-tab.has-hover ? #404040 : #303030);

                ta-tab := TouchArea {
                    clicked => {
                        if Globals.preview-mode {
                            current-tab-index = index;
                        } else {
                            Globals.tab-clicked(section, index);
                        }
                    }
                }

                HorizontalLayout {
                    padding-left: 4px;
                    padding-right: 2px;
                    spacing: 3px;

                    Image {
                        width: 16px;
                        source: (tab.type == TabType.board) ? @image-url("img/projects.png") : @image-url("img/image.svg");
                    }

                    t-tab := Text {
                        vertical-alignment: TextVerticalAlignment.center;
                        color: (index == current-tab-index) ? white : #a0a0a0;
                        text: tab.title;
                    }

                    Rectangle {
                        y: (parent.height - self.height) / 2;
                        width: icon.width;
                        height: icon.height;
                        background: ta-close.has-hover ? #454545 : transparent;
                        border-radius: 3px;

                        icon := Image {
                            source: @image-url("img/close.svg");
                            colorize: t-tab.color;
                        }

                        ta-close := TouchArea { }
                    }
                }
            }
        }
    }

    scene := Image {
        x: 0;
        y: tabBar.height;
        width: 100%;
        height: parent.height - self.y;
        image-fit: ImageFit.preserve;
        image-rendering: ImageRendering.pixelated;
        source: Globals.render-scene(section, self.width, self.height, scene-frame);

        TouchArea {
            pointer-event(e) => {
                return Globals.scene-pointer_event(section, self.mouse-x, self.mouse-y, self.pressed-x, self.pressed-y, e);
            }
            scroll-event(e) => {
                return Globals.scene-scrolled(section, self.mouse-x, self.mouse-y, e);
            }
        }
    }
}
