import { ProgressBar, LengthEdit, Palette } from "widgets.slint";
import { NotificationsPopup } from "notificationspopup.slint";
import {
    Constants,
    Data,
    NotificationType,
    Backend,
    Action,
    Helpers,
    GridStyle,
    TabType
} from "api.slint";

export component StatusBar inherits Rectangle {
    height: 25px;
    background: #353535;

    HorizontalLayout {
        padding-left: 10px;

        Rectangle {
            horizontal-stretch: 1;

            status-txt := Text {
                width: 100%;
                height: 100%;
                vertical-alignment: center;
                accessible-description: "status text";

                states [
                    status-tip when !Data.status-tip.is-empty: {
                        text: Data.status-tip;
                        color: white;
                    }
                    message when !Data.status-bar-message.is-empty: {
                        text: Data.status-bar-message;
                        color: white;
                    }
                    default when true: {
                        text: Data.workspace-path;
                    }
                ]
            }
        }

        Rectangle {
            width: 10px;
        }

        Text {
            vertical-alignment: center;
            font-family: "Noto Sans Mono";
            font-size: 11px;
            color: white;
            text: Data.cursor-coordinates;
            visible: Data.current-tab-is-2d;
        }

        Rectangle {
            width: 15px;
        }

        Rectangle {
            width: t-grid-interval.preferred-width + self.height - t-grid-interval.preferred-height;
            background: t-grid-interval.has-hover ? #505050 : #404040;

            t-grid-interval := TouchArea {
                enabled: Data.current-tab-is-2d;

                Text {
                    vertical-alignment: center;
                    font-family: "Noto Sans Mono";
                    font-size: 11px;
                    color: (!Data.current-tab-is-2d) ? #707070 : white;
                    text: Data.current-grid-interval;
                }

                clicked => {
                    pw-grid-interval.show();
                }
            }

            pw-grid-interval := PopupWindow {
                x: -(self.width - parent.width) / 2;
                y: -self.height;
                width: le-grid-interval.preferred-width;
                height: le-grid-interval.preferred-height;
                close-policy: close-on-click-outside;
                forward-focus: le-grid-interval;

                le-grid-interval := LengthEdit { }
            }
        }

        VerticalLayout {
            width: self.height * 0.7;

            ta-grid-interval-increase := TouchArea {
                enabled: Data.current-tab-is-2d;

                Rectangle {
                    background: parent.has-hover ? #505050 : #404040;

                    Image {
                        width: 100%;
                        height: ta-grid-interval-increase.pressed ? 80% : 100%;
                        image-fit: contain;
                        source: @image-url("../../../font-awesome/svgs/solid/caret-up.svg");
                        colorize: (!Data.current-tab-is-2d) ? #707070 : white;
                    }
                }

                clicked => {
                    Backend.trigger(Action.section-grid-interval-increase, Data.current-section-index);
                }
            }

            ta-grid-interval-decrease := TouchArea {
                enabled: Data.current-tab-is-2d;

                Rectangle {
                    background: parent.has-hover ? #505050 : #404040;

                    Image {
                        width: 100%;
                        height: ta-grid-interval-decrease.pressed ? 80% : 100%;
                        image-fit: contain;
                        source: @image-url("../../../font-awesome/svgs/solid/caret-down.svg");
                        colorize: (!Data.current-tab-is-2d) ? #707070 : white;
                    }
                }

                clicked => {
                    Backend.trigger(Action.section-grid-interval-decrease, Data.current-section-index);
                }
            }
        }

        Rectangle {
            width: max(t-unit.preferred-width + self.height - t-unit.preferred-height, 38px);
            background: t-unit.has-hover ? #505050 : #404040;

            t-unit := TouchArea {
                enabled: Data.current-tab-is-2d;

                Text {
                    vertical-alignment: center;
                    font-size: 11px;
                    color: (!Data.current-tab-is-2d) ? #707070 : white;
                    text: Helpers.get-unit-short-str(Data.current-unit);
                }

                clicked => {
                    pw-unit.show();
                }
            }

            pw-unit := PopupWindow {
                x: -(self.preferred-width - parent.width) / 2;
                y: -self.preferred-height;

                VerticalLayout {
                    for unit in Data.all-length-units: TouchArea {
                        Rectangle {
                            background: parent.has-hover ? #505050 : #404040;

                            HorizontalLayout {
                                padding: 5px;

                                Text {
                                    color: #cccccc;
                                    horizontal-alignment: center;
                                    text: Helpers.get-unit-short-str(unit);
                                }
                            }
                        }

                        clicked => {
                            Data.set-current-unit(unit);
                        }
                    }
                }
            }
        }

        Rectangle {
            width: self.height;
            background: t-grid-style.has-hover ? #505050 : #404040;

            t-grid-style := TouchArea {
                enabled: Data.current-tab-is-2d;

                Image {
                    width: self.height * 0.7;
                    height: 100%;
                    image-fit: contain;
                    source: (Data.current-grid-style == GridStyle.lines) ? @image-url("../../../bootstrap-icons/icons/grid-3x3.svg") : ((Data.current-grid-style == GridStyle.dots) ? @image-url("../../../../img/grid-dots.svg") : @image-url("../../../../img/grid-none.svg"));
                    colorize: (!Data.current-tab-is-2d) ? #707070 : Palette.foreground;
                }

                clicked => {
                    if (Data.current-grid-style == GridStyle.none) {
                        Data.set-current-grid-style(GridStyle.dots);
                    } else if (Data.current-grid-style == GridStyle.dots) {
                        Data.set-current-grid-style(GridStyle.lines);
                    } else {
                        Data.set-current-grid-style(GridStyle.none);
                    }
                }
            }
        }

        Rectangle {
            width: self.height;
            background: (ta-lock.enabled && Data.ignore-placement-locks) ? #900000 : (ta-lock.has-hover ? #505050 : #404040);

            ta-lock := TouchArea {
                enabled: Data.current-tab.type == TabType.board-2d;

                Image {
                    width: self.height * 0.7;
                    height: 100%;
                    image-fit: contain;
                    source: Data.ignore-placement-locks ? @image-url("../../../font-awesome/svgs/solid/lock-open.svg") : @image-url("../../../font-awesome/svgs/solid/lock.svg");
                    colorize: (!ta-lock.enabled) ? #707070 : (Data.ignore-placement-locks ? white : Palette.foreground);
                }

                clicked => {
                    Data.ignore-placement-locks = !Data.ignore-placement-locks;
                }
            }
        }

        Rectangle {
            width: 10px;
        }

        Rectangle {
            max-width: 150px;

            progress-bar := ProgressBar {
                width: 100%;
                visible: Data.notifications[Data.notifications-progress-index].type == NotificationType.progress;
                progress: Data.notifications[Data.notifications-progress-index].progress / 100;
            }
        }

        Rectangle {
            width: 10px;
        }

        Rectangle {
            property <bool> enabled: Data.notifications.length > 0;
            property <int> item-count: Data.notifications.length;

            changed item-count => {
                if item-count == 0 {
                    Data.notifications-shown = false;
                }
            }

            width: self.height;
            background: notifications-ta.has-hover ? #505050 : transparent;
            border-width: (Data.notifications-unread > 0) ? 1px : 0px;
            border-color: Constants.librepcb-color;

            notifications-ta := TouchArea {
                enabled: enabled;

                Image {
                    width: self.height * 0.7;
                    height: 100%;
                    image-fit: contain;
                    colorize: enabled ? white : #707070;
                    source: {
                        if Data.notifications-unread > 0 {
                            @image-url("../../../font-awesome/svgs/solid/bell.svg")
                        } else {
                            @image-url("../../../font-awesome/svgs/regular/bell.svg")
                        }
                    };

                    // Accessibility
                    accessible-role: button;
                    accessible-enabled: enabled;
                    accessible-expandable: true;
                    accessible-expanded: Data.notifications-shown;
                    accessible-label: "\{Data.notifications-unread} Notifications";
                    accessible-action-default => {
                        parent.clicked();
                    }
                    accessible-action-expand => {
                        parent.clicked();
                    }
                }

                if Data.notifications-unread > 0: notifications-unread-txt := Text {
                    y: (parent.height - self.height) / 2 - 2px;
                    color: root.background;
                    horizontal-alignment: center;
                    font-size: 12px;
                    font-weight: 900;
                    text: Data.notifications-unread;
                    accessible-role: none;
                }

                clicked => {
                    Data.notifications-shown = !Data.notifications-shown;
                }
            }

            notifications-popup := NotificationsPopup {
                x: parent.width - self.width;
                y: -self.height;
                width: min(max(self.preferred-width, 300px), root.width * 0.5, 700px);
                height: Data.notifications-shown ? self.preferred-height : 0;
                visible: self.height > 0;
                clip: true;

                animate height { duration: 100ms; }
            }
        }
    }
}
