import { ProgressIndicator, Palette } from "std-widgets.slint";
import { LengthEdit } from "./common/lengthedit.slint";
import { NotificationsPopup } from "./notificationspopup.slint";
import { MainPage, GridStyle, TabType, NotificationType, ActionId } from "./api/types.slint";
import { Data } from "./api/data.slint";
import { Backend } from "api/backend.slint";

export component StatusBar inherits Rectangle {
    height: 25px;
    background: #353535;

    HorizontalLayout {
        padding-left: 10px;

        Rectangle {
            horizontal-stretch: 1;

            Text {
                width: 100%;
                height: 100%;
                vertical-alignment: center;

                states [
                    status-tip when !Data.current-status-tip.is-empty: {
                        text: Data.current-status-tip;
                        color: white;
                    }
                    message when !Data.status-bar-message.is-empty: {
                        text: Data.status-bar-message;
                        color: white;
                    }
                    default when true: {
                        text: Data.workspace-path;
                    }
                ]
            }
        }

        Rectangle {
            width: 10px;
        }

        Text {
            vertical-alignment: center;
            font-family: "Noto Sans Mono";
            font-size: 11px;
            color: white;
            text: Data.cursor-coordinates;
            visible: Data.current-tab-is-2d;
        }

        Rectangle {
            width: 15px;
        }

        Rectangle {
            width: t-grid-interval.preferred-width + self.height - t-grid-interval.preferred-height;
            background: t-grid-interval.has-hover ? #505050 : #404040;

            t-grid-interval := TouchArea {
                enabled: Data.current-tab-is-2d;

                Text {
                    vertical-alignment: center;
                    font-family: "Noto Sans Mono";
                    font-size: 11px;
                    color: (!Data.current-tab-is-2d) ? #707070 : white;
                    text: Data.current-grid-interval;
                }

                clicked => {
                    pw-grid-interval.show();
                }
            }

            pw-grid-interval := PopupWindow {
                x: -(self.preferred-width - parent.width) / 2;
                y: -self.preferred-height;
                close-policy: close-on-click-outside;

                LengthEdit { }
            }
        }

        VerticalLayout {
            width: self.height * 0.7;

            ta-grid-interval-increase := TouchArea {
                enabled: Data.current-tab-is-2d;

                Rectangle {
                    background: parent.has-hover ? #505050 : #404040;

                    Image {
                        width: 100%;
                        height: ta-grid-interval-increase.pressed ? 80% : 100%;
                        image-fit: contain;
                        source: @image-url("../../../../img/caret-up.svg");
                        colorize: (!Data.current-tab-is-2d) ? #707070 : white;
                    }
                }

                clicked => {
                    Backend.action-triggered(ActionId.section-grid-interval-increase, Data.current-section-index);
                }
            }

            ta-grid-interval-decrease := TouchArea {
                enabled: Data.current-tab-is-2d;

                Rectangle {
                    background: parent.has-hover ? #505050 : #404040;

                    Image {
                        width: 100%;
                        height: ta-grid-interval-decrease.pressed ? 80% : 100%;
                        image-fit: contain;
                        source: @image-url("../../../../img/caret-down.svg");
                        colorize: (!Data.current-tab-is-2d) ? #707070 : white;
                    }
                }

                clicked => {
                    Backend.action-triggered(ActionId.section-grid-interval-decrease, Data.current-section-index);
                }
            }
        }

        Rectangle {
            width: max(t-unit.preferred-width + self.height - t-unit.preferred-height, 38px);
            background: t-unit.has-hover ? #505050 : #404040;

            t-unit := TouchArea {
                enabled: Data.current-tab-is-2d;

                Text {
                    vertical-alignment: center;
                    font-size: 11px;
                    color: (!Data.current-tab-is-2d) ? #707070 : white;
                    text: Data.get-unit-short-str(Data.current-unit);
                }

                clicked => {
                    pw-unit.show();
                }
            }

            pw-unit := PopupWindow {
                x: -(self.preferred-width - parent.width) / 2;
                y: -self.preferred-height;

                VerticalLayout {
                    for unit in Data.all-length-units: TouchArea {
                        Rectangle {
                            background: parent.has-hover ? #505050 : #404040;

                            HorizontalLayout {
                                padding: 5px;

                                Text {
                                    color: #cccccc;
                                    horizontal-alignment: center;
                                    text: Data.get-unit-short-str(unit);
                                }
                            }
                        }

                        clicked => {
                            Data.set-current-unit(unit);
                        }
                    }
                }
            }
        }

        Rectangle {
            width: self.height;
            background: t-grid-style.has-hover ? #505050 : #404040;

            t-grid-style := TouchArea {
                enabled: Data.current-tab-is-2d;

                Image {
                    width: self.height * 0.7;
                    height: 100%;
                    image-fit: contain;
                    source: (Data.current-grid-style == GridStyle.lines) ? @image-url("../../../../img/grid-lines.svg") : ((Data.current-grid-style == GridStyle.dots) ? @image-url("../../../../img/grid-dots.svg") : @image-url("../../../../img/grid-none.svg"));
                    colorize: (!Data.current-tab-is-2d) ? #707070 : Palette.foreground;
                }

                clicked => {
                    if (Data.current-grid-style == GridStyle.none) {
                        Data.set-current-grid-style(GridStyle.dots);
                    } else if (Data.current-grid-style == GridStyle.dots) {
                        Data.set-current-grid-style(GridStyle.lines);
                    } else {
                        Data.set-current-grid-style(GridStyle.none);
                    }
                }
            }
        }

        Rectangle {
            width: self.height;
            background: (ta-lock.enabled && Data.ignore-placement-locks) ? #900000 : (ta-lock.has-hover ? #505050 : #404040);

            ta-lock := TouchArea {
                enabled: Data.current-tab.type == TabType.board-2d;

                Image {
                    width: self.height * 0.7;
                    height: 100%;
                    image-fit: contain;
                    source: Data.ignore-placement-locks ? @image-url("../../../../img/lock-open.svg") : @image-url("../../../../img/lock-closed.svg");
                    colorize: (!ta-lock.enabled) ? #707070 : (Data.ignore-placement-locks ? white : Palette.foreground);
                }

                clicked => {
                    Data.ignore-placement-locks = !Data.ignore-placement-locks;
                }
            }
        }

        Rectangle {
            width: 10px;
        }

        Rectangle {
            max-width: 150px;

            ProgressIndicator {
                width: 100%;
                visible: Data.notifications[Data.current-progress-notification-index].type == NotificationType.progress;
                progress: Data.notifications[Data.current-progress-notification-index].progress / 100;
            }
        }

        Rectangle {
            width: 10px;
        }

        Rectangle {
            property <bool> enabled: Data.notifications.length > 0;
            property <int> item-count: Data.notifications.length;

            changed item-count => {
                if item-count == 0 {
                    Data.notifications-shown = false;
                }
            }

            width: self.height;
            background: ta-notifications.has-hover ? #505050 : transparent;
            border-width: (Data.unread-notifications-count > 0) ? 1px : 0px;
            border-color: #29d682;

            ta-notifications := TouchArea {
                enabled: enabled;

                Image {
                    width: self.height * 0.7;
                    height: 100%;
                    image-fit: contain;
                    source: (Data.unread-notifications-count > 0) ? @image-url("../../../../img/bell-solid.svg") : @image-url("../../../../img/bell.svg");
                    colorize: enabled ? white : #707070;
                }

                if Data.unread-notifications-count > 0: Text {
                    color: root.background;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    font-size: 12px;
                    font-weight: 900;
                    text: Data.unread-notifications-count;
                }

                clicked => {
                    Data.notifications-shown = !Data.notifications-shown;
                }
            }

            NotificationsPopup {
                x: parent.width - self.width;
                y: -self.height;
                width: min(max(self.preferred-width, 300px), root.width * 0.5, 700px);
                height: Data.notifications-shown ? self.preferred-height : 0;
                visible: self.height > 0;
                clip: true;
                popup-shown: Data.notifications-shown;

                animate height { duration: 100ms; }

                close-requested => {
                    Data.notifications-shown = false;
                }
            }
        }
    }
}
