import { TabType, TabData, WindowSectionData, Action } from "./api/types.slint";
import { Tab } from "./tab.slint";
import { HomeTab } from "./hometab.slint";
import { CreateLibraryTab } from "./library/createlibrarytab.slint";
import { DownloadLibraryTab } from "./library/downloadlibrarytab.slint";
import { Backend } from "./api/backend.slint";
import { Data, Helpers } from "api.slint";

component TabButton inherits Rectangle {
    in property <TabData> tab;
    in property <int> index;
    in property <bool> is-current-section: false;
    in property <bool> is-current-tab: false;

    callback clicked <=> ta-tab.clicked;
    callback close-clicked;

    background: is-current-tab ? #505050 : (ta-tab.has-hover ? #454545 : #3a3a3a);

    // Accessibility
    accessible-role: AccessibleRole.tab;
    accessible-label: ((index == 0) && tab.title.is-empty) ? "home" : tab.title;
    accessible-action-default => {
        ta-tab.clicked();
    }

    ta-tab := TouchArea { }

    HorizontalLayout {
        padding-left: 4px;
        padding-right: 2px;
        spacing: 3px;

        Image {
            width: 16px;
            source: Helpers.get-icon-for-tab-type(tab.type);
            colorize: t-tab.color;
            accessible-role: none;
        }

        t-tab := Text {
            vertical-alignment: TextVerticalAlignment.center;
            color: is-current-tab ? white : #a0a0a0;
            text: tab.title;
            accessible-role: none;
        }

        if tab.type != TabType.home: Rectangle {
            y: (parent.height - self.height) / 2;
            width: self.height;
            height: t-tab.height * 0.6;
            background: ta-tab-close.has-hover ? #454545 : transparent;
            border-radius: 3px;

            // Accessibility
            accessible-role: button;
            accessible-label: "close tab";
            accessible-action-default => {
                ta-tab-close.clicked();
            }

            i-tab-close := Image {
                x: (parent.width - self.width) / 2;
                y: (parent.height - self.height) / 2;
                width: ta-tab-close.pressed ? 50% : 60%;
                height: self.width;
                image-fit: contain;
                source: @image-url("../../../font-awesome/svgs/solid/xmark.svg");
                colorize: t-tab.color;
                accessible-role: none;
            }

            ta-tab-close := TouchArea {
                clicked => {
                    close-clicked();
                }
            }
        }
    }

    if (is-current-section) && (is-current-tab): Rectangle {
        x: 0;
        y: 0;
        width: 100%;
        height: 1px;
        background: #29d682;
    }
}

export component WindowSection inherits Rectangle {
    in-out property <int> section-index;
    in-out property <WindowSectionData> section;
    property <bool> is-current-section: (section-index == Data.current-section-index);
    property <int> first-tab-index: (section-index == 0) ? 0 : 1;
    property <bool> tab-open: (section.current-tab-index >= first-tab-index) && (section.current-tab-index < section.tabs.length);
    property <TabType> tab-type: section.tabs[section.current-tab-index].type;

    TouchArea {
        tab-bar := Rectangle {
            x: 0;
            y: 0;
            height: 30px;
            background: #2c2c2c;

        // Accessibility
        accessible-role: tab-list;

            Rectangle {
                x: 0;
                width: controls.x;
                clip: true;

                HorizontalLayout {
                    alignment: LayoutAlignment.start;
                    width: 100%;

                    for tab[index] in section.tabs: TabButton {
                        tab: tab;
                        index: index;
                        is-current-section: is-current-section;
                        is-current-tab: (index == section.current-tab-index);
                        visible: index >= first-tab-index;
                        width: self.visible ? self.preferred-width : 0;

                        clicked => {
                            Data.current-section-index = section-index;
                            if Data.preview-mode {
                                Data.sections[section-index].current-tab-index = index;
                            } else {
                                section.tabs[index].action = Action.tab-activate;
                            }
                        }

                        close-clicked => {
                            section.tabs[section.current-tab-index].action = Action.tab-close;
                        }
                    }
                }
            }

            controls := HorizontalLayout {
                x: parent.width - self.width;
                width: self.preferred-width;
                padding: 3px;

                Rectangle {
                    width: self.height;
                    background: ta-section-split.has-hover ? #454545 : transparent;
                    border-radius: 3px;

                // Accessibility
                accessible-role: button;
                    accessible-label: "split section";
                    accessible-action-default => {
                        ta-section-split.clicked();
                    }

                    Image {
                        height: parent.height - 10px;
                        source: @image-url("../../../bootstrap-icons/icons/layout-split.svg");
                        colorize: #c0c0c0;
                        accessible-role: none;
                    }

                    ta-section-split := TouchArea {
                        clicked => {
                            Data.sections[section-index].action = Action.section-split;
                        }
                    }
                }

                if (Data.sections.length > 1) && (section.tabs.length <= 1): Rectangle {
                    width: self.height;
                    background: ta-section-close.has-hover ? #454545 : transparent;
                    border-radius: 3px;

                // Accessibility
                accessible-role: button;
                    accessible-label: "close section";
                    accessible-action-default => {
                        ta-section-close.clicked();
                    }

                    Image {
                        width: self.height;
                        height: parent.height - 10px;
                        image-fit: contain;
                        source: @image-url("../../../font-awesome/svgs/solid/xmark.svg");
                        colorize: #c0c0c0;
                        accessible-role: none;
                    }

                    ta-section-close := TouchArea {
                        clicked => {
                            Data.sections[section-index].action = Action.section-close;
                        }
                    }
                }
            }
        }

        Rectangle {
            x: 0;
            y: tab-bar.height;
            width: root.width;
            height: parent.height - self.y;

            // Accessibility
            accessible-role: tab-panel;

            if !tab-open: Tab {
                show-watermark: true;
            }

            if tab-open && (tab-type == TabType.home): HomeTab {
                width: 100%;
                height: 100%;
                section-index: section-index;
            }

            if tab-open && (tab-type == TabType.create-library): CreateLibraryTab {
                width: 100%;
                height: 100%;
                section-index: section-index;
                section: section;
            }

            if tab-open && (tab-type == TabType.download-library): DownloadLibraryTab {
                width: 100%;
                height: 100%;
                section-index: section-index;
                section: section;
            }

        // Highlight rectangle
        property <float> highlight-percentage:section.highlight ? 1.2 : 0;
            animate highlight-percentage { duration: 700ms; }
            if (highlight-percentage > 0): Rectangle {
                border-color: #29d682;
                border-width: 3px;
                opacity: (!section.highlight) ? 0 : (1.2 - highlight-percentage);
            }
        }

        pointer-event(e) => {
            if (e.kind == PointerEventKind.down) {
                Data.current-section-index = section-index;
            }
            EventResult.accept
        }
    }
}
