import { IconButton } from "iconbutton.slint";
import {
    Constants,
    HAlign,
    Helpers,
    VAlign,
} from "../api.slint";

component AlignmentButton inherits IconButton {
    width: 18px;
    style: checkable-hyperlink;
    color-enabled: #606060;
    color-checked: #c0c0c0;
}

component AlignmentSelector inherits Rectangle {
    in property <[image]> icons;
    in property <[string]> tooltips;
    in property <int> index: 0;
    in property <bool> enabled: true;

    callback index-clicked(int);

    width: self.preferred-width;
    preferred-height: 28px;
    background: #202020;
    border-color: {
        if fs.has-focus {
            Constants.librepcb-color
        } else if enabled {
            #606060
        } else {
            transparent
        }
    }
    border-width: 1px;
    border-radius: 10px;
    forward-focus: fs;

    fs := FocusScope {
        HorizontalLayout {
            padding: 5px;
            spacing: 3px;

            AlignmentButton {
                icon: icons[0];
                tooltip: tooltips[0];
                checked: index == 0;

                clicked => {
                    index-clicked(0);
                }
            }

            AlignmentButton {
                icon: icons[1];
                tooltip: tooltips[1];
                checked: index == 1;

                clicked => {
                    index-clicked(1);
                }
            }

            AlignmentButton {
                icon: icons[2];
                tooltip: tooltips[2];
                checked: index == 2;

                clicked => {
                    index-clicked(2);
                }
            }
        }

        key-pressed(event) => {
            if event.text == Key.LeftArrow {
                if index > 0 {
                    index-clicked(index - 1);
                }
                return accept;
            } else if event.text == Key.RightArrow {
                if index < 2 {
                    index-clicked(index + 1);
                }
                return accept;
            }
            reject
        }
    }
}

export component HAlignSelector inherits AlignmentSelector {
    in-out property <HAlign> align;

    icons: [
        @image-url("../../../../font-awesome/svgs/solid/align-left.svg"),
        @image-url("../../../../font-awesome/svgs/solid/align-center.svg"),
        @image-url("../../../../font-awesome/svgs/solid/align-right.svg"),
    ];
    tooltips: [
        @tr("Align Left"),
        @tr("Align Center"),
        @tr("Align Right"),
    ];
    index: {
        if align == HAlign.left {
            return 0;
        } else if align == HAlign.center {
            return 1;
        } else {
            return 2;
        }
    };

    callback value-clicked(HAlign);
    value-clicked(a) => {
        align = a;
    }

    index-clicked(index) => {
        if index == 0 {
            value-clicked(HAlign.left);
        } else if index == 1 {
            value-clicked(HAlign.center);
        } else {
            value-clicked(HAlign.right);
        }
    }
}

export component VAlignSelector inherits AlignmentSelector {
    in-out property <VAlign> align;

    icons: [
        @image-url("../../../../bootstrap-icons/icons/align-bottom.svg"),
        @image-url("../../../../bootstrap-icons/icons/align-center.svg"),
        @image-url("../../../../bootstrap-icons/icons/align-top.svg"),
    ];
    tooltips: [
        @tr("Align Bottom"),
        @tr("Align Center"),
        @tr("Align Top"),
    ];
    index: {
        if align == VAlign.bottom {
            return 0;
        } else if align == VAlign.center {
            return 1;
        } else {
            return 2;
        }
    };

    callback value-clicked(VAlign);
    value-clicked(a) => {
        align = a;
    }

    index-clicked(index) => {
        if index == 0 {
            value-clicked(VAlign.bottom);
        } else if index == 1 {
            value-clicked(VAlign.center);
        } else {
            value-clicked(VAlign.top);
        }
    }
}
