import { Palette } from "std-widgets.slint";
import { LibraryElementCategoryData } from "../api.slint";
import { IconButton } from "iconbutton.slint";
import { CategoryTreeLabel } from "categorytreelabel.slint";

component CategoriesListViewRow inherits TouchArea {
    Rectangle {
        height: self.preferred-height;
        background: #393939;
        border-radius: 2px;

        HorizontalLayout {
            padding: 2px;
            padding-left: 4px;
            padding-right: 4px;
            spacing: 5px;

            @children
        }
    }
}

export component CategoriesListView inherits HorizontalLayout {
    in-out property <[LibraryElementCategoryData]> model;
    in property <bool> read-only: false;

    callback add-triggered();

    alignment: start;

    VerticalLayout {
        horizontal-stretch: 0;
        spacing: 5px;

        for item[index] in model: item-ta := CategoriesListViewRow {
            CategoryTreeLabel {
                names: item.names;
            }

            if !read-only: Rectangle {
                width: 10px;
                visible: item-ta.has-hover;
            }

            if !read-only: Rectangle {
                width: 1px;
                background: #707070;
                visible: item-ta.has-hover;
            }

            if !read-only: IconButton {
                width: 16px;
                style: hyperlink;
                icon: @image-url("../../../../font-awesome/svgs/solid/trash-can.svg");
                visible: item-ta.has-hover;

                clicked => {
                    model[index].delete = true;
                }
            }
        }

        if !read-only: CategoriesListViewRow {
            mouse-cursor: pointer;

            Image {
                width: 16px;
                height: self.width;
                image-fit: contain;
                colorize: add-txt.color;
                source: @image-url("../../../../bootstrap-icons/icons/plus-circle.svg");
            }

            add-txt := Text {
                color: parent.has-hover ? white : Palette.foreground;
                vertical-alignment: center;
                overflow: elide;
                text: @tr("Add Category");
            }

            clicked => {
                add-triggered();
            }
        }
    }
}
