import { Palette, ScrollView } from "std-widgets.slint";
import { DropDownPopup } from "dropdownpopup.slint";
import { IconButton } from "iconbutton.slint";
import { Constants } from "../api.slint";

export component LineEdit inherits Rectangle {
    in-out property <string> text;
    in property <string> placeholder-text;
    in property <string> validation-error;
    in property <bool> enabled: true;
    in property <bool> read-only: false;
    in property <length> font-size: 13px;
    in property <[string]> suggestions;
    out property <bool> has-focus <=> edt.has-focus;
    property <int> current-suggestion-index: -1;

    callback text-edited(string);
    text-edited(text) => {
        self.text = text;
    }

    callback key-pressed(KeyEvent) -> EventResult;

    public function select-all() {
        edt.select-all();
    }

    function select-suggestion(index: int) {
        current-suggestion-index = max(min(index, suggestions.length - 1), -1);
        text-edited(suggestions[current-suggestion-index]);
    }

    changed text => {
        if text != edt.text {
            edt.text = text;
        }
    }

    changed has-focus => {
        if !has-focus {
            edt.text = text;
        }
    }

    preferred-width: max(l.preferred-width, placeholder-txt.preferred-width + 2 * placeholder-txt.x, 100px);
    preferred-height: 28px;
    horizontal-stretch: 1;
    background: #202020;
    border-color: {
        if enabled && (!validation-error.is-empty) {
            edt.has-focus ? #ff0000 : #900000
        } else if edt.has-focus {
            Constants.librepcb-color
        } else if enabled {
            #606060
        } else {
            transparent
        }
    }
    border-width: 1px;
    border-radius: 10px;
    forward-focus: edt;

    // Accessibility
    accessible-role: text-input;
    accessible-enabled: enabled;
    accessible-expandable: suggestions.length > 0;
    accessible-value: edt.text;
    accessible-placeholder-text: placeholder-text;
    accessible-read-only: read-only;
    accessible-action-expand => {
        suggestions-popup.show();
    }
    accessible-action-set-value(t) => {
        edt.text = t;
    }

    placeholder-txt := Text {
        x: 10px;
        width: root.width - 2 * self.x;
        font-size: font-size;
        color: enabled ? #909090 : #707070;
        text: placeholder-text;
        wrap: no-wrap;
        overflow: elide;
        visible: edt.text.is-empty && (!placeholder-text.is-empty);
    }

    ta := TouchArea {
        enabled: enabled;

        l := HorizontalLayout {
            x: 0;
            y: 0;
            padding-left: placeholder-txt.x;
            padding-right: 3px;

            view := ScrollView {
                min-width: edt.min-width;
                preferred-width: edt.preferred-width;
                viewport-width: edt.width;
                viewport-height: edt.height;

                edt := TextInput {
                    property <length> y-offset: (self.width > parent.width) ? 3px : 0;

                    y: ((parent.height - self.height) / 2) - y-offset;
                    width: max(self.preferred-width, view.width);
                    height: self.preferred-height;
                    font-size: font-size;
                    color: enabled ? Palette.foreground : Palette.foreground.darker(0.5);
                    selection-background-color: Constants.librepcb-color;
                    selection-foreground-color: black;
                    enabled: enabled;
                    read-only: read-only;
                    single-line: true;
                    wrap: no-wrap;
                    text: text;
                    accessible-role: none;

                    edited => {
                        text-edited(self.text);
                    }

                    key-pressed(event) => {
                        if root.key-pressed(event) == accept {
                            return accept;
                        } else if event.text == Key.UpArrow {
                            select-suggestion(current-suggestion-index - 1);
                            return accept;
                        } else if event.text == Key.DownArrow {
                            select-suggestion(current-suggestion-index + 1);
                            return accept;
                        } else if (event.text == Key.Space) && event.modifiers.control {
                            suggestions-popup.show();
                            return accept;
                        }
                        reject;
                    }
                }
            }

            Rectangle {
                width: 5px;
            }

            clear-btn := IconButton {
                y: (parent.height - self.height) / 2;
                height: 18px;
                background-color: root.background;
                border-radius: self.height / 2;
                icon-scale: 0.7;
                icon: @image-url("../../../../font-awesome/svgs/solid/xmark.svg");
                visible: ta.has-hover && (!edt.text.is-empty);
                accessible-role: none;

                clicked => {
                    edt.text = "";
                }
            }

            if suggestions.length > 0: expand-btn := IconButton {
                y: (parent.height - self.height) / 2;
                height: 18px;
                background-color: root.background;
                border-radius: self.height / 2;
                icon-size: 13px;  // Same size as in ComboBox.
                icon: @image-url("../../../../font-awesome/svgs/solid/caret-down.svg");
                accessible-role: none;

                clicked => {
                    suggestions-popup.show();
                }
            }
        }
    }

    if enabled && (!validation-error.is-empty): Rectangle {
        x: root.width - self.width - 20px;
        y: -8px;
        width: min(validation-error-txt.preferred-width + 10px, root.width * 0.8);
        height: validation-error-txt.preferred-height + 4px;
        background: #101010;
        border-width: 1px;
        border-radius: self.height / 2;
        border-color: root.border-color;

        validation-error-txt := Text {
            x: 5px;
            width: parent.width - 10px;
            vertical-alignment: center;
            font-size: 11px;
            overflow: elide;
            color: root.border-color;
            text: validation-error;
            accessible-description: "validation error";
        }
    }

    suggestions-popup := DropDownPopup {
        x: 0;
        y: parent.height;
        width: root.width;
        model: suggestions;
        current-text: root.text;
        item-height: root.preferred-height;

        accepted(index) => {
            text-edited(suggestions[index]);
        }
    }
}
