import { Palette } from "std-widgets.slint";
import { Spinner } from "spinner.slint";
import { ToolTip } from "tooltip.slint";
import { Constants, Data } from "../api.slint";

export component PanelHeaderButton inherits Rectangle {
    in property <image> icon;
    in property <float> icon-scale: 0.8;
    in property <color> colorize: transparent;
    in property <string> tooltip;
    in property <bool> tooltip-delayed: true;
    in property <string> status-tip;
    in property <bool> enabled: true;
    in property <bool> read-only: false;

    callback clicked;

    width: self.height;
    background: ((!read-only) && ta.has-hover) ? #454545 : transparent;

    // Accessibility
    accessible-role: button;
    accessible-description: status-tip;
    accessible-enabled: enabled;
    accessible-label: tooltip;
    accessible-read-only: read-only;
    accessible-action-default => {
        ta.clicked();
    }

    ta := TouchArea {
        enabled: enabled;

        Image {
            x: (parent.width - self.width) / 2;
            y: self.x;
            width: self.height;
            height: parent.height * icon-scale * (((!read-only) && ta.pressed) ? 0.85 : 1.0);
            image-fit: contain;
            source: icon;
            colorize: (colorize != transparent) ? colorize : (((!read-only) && ta.has-hover) ? white : (enabled ? Palette.foreground : #707070));
            accessible-role: none;
        }

        if self.has-hover && (!self.pressed) && (!tooltip.is-empty): tt := ToolTip {
            x: (parent.width - self.width) / 2;
            y: parent.height + 5px;
            text: tooltip;
            delayed: tooltip-delayed;
        }

        changed has-hover => {
            if !root.status-tip.is-empty {
                if self.has-hover {
                    Data.status-tip = root.status-tip;
                } else {
                    Data.status-tip = "";
                }
            }
        }

        clicked => {
            if !root.status-tip.is-empty {
                Data.status-tip = "";
            }
            root.clicked();
        }
    }
}

export component PanelHeader inherits Rectangle {
    in property <length> spacing-top;
    in property <string> title;
    in property <string> note;
    in property <bool> show-spinner: false;
    in property <bool> highlight: false;
    property <length> content-height: 25px;

    height: spacing-top + content-height + 1px;

    // Accessibility
    accessible-role: text;
    accessible-label: title;

    VerticalLayout {
        padding-top: spacing-top;

        HorizontalLayout {
            height: content-height;
            padding-left: 5px;
            padding-right: 1px;
            spacing: 3px;

            title-txt := Text {
                y: 2px;
                font-weight: 700;
                overflow: elide;
                vertical-alignment: center;
                text: title;
                accessible-role: none;
            }

            if !note.is-empty: note-txt := Text {
                y: 2px;
                horizontal-stretch: 1;
                font-size: 11px;
                font-italic: true;
                vertical-alignment: center;
                overflow: elide;
                text: note;
            }

            HorizontalLayout {
                if show-spinner: spinner := Spinner {
                    indeterminate: true;
                    width: content-height - 8px;
                    height: content-height;
                }

                @children
            }
        }

        Rectangle {
            height: 1px;
            background: {
                if highlight {
                    @linear-gradient(90deg, Constants.librepcb-color 0%, #555555 100%)
                } else {
                    #555555
                }
            };
        }
    }
}
