import { Constants } from "../api.slint";

export component ToolBarWidget inherits FocusScope {
    in property <length> spacing: 3px;

    width: self.preferred-width;
    preferred-height: 28px;
    padding-left: 5px;
    padding-right: 5px;
    padding-top: 5px;
    padding-bottom: 5px;

    Rectangle {
        background: #202020;
        border-color: {
            if root.has-focus {
                Constants.librepcb-color
            } else if root.enabled {
                #606060
            } else {
                transparent
            }
        }
        border-width: 1px;
        border-radius: 10px;

        HorizontalLayout {
            padding-left: root.padding-left;
            padding-right: root.padding-right;
            padding-top: root.padding-top;
            padding-bottom: root.padding-bottom;
            spacing: spacing;

            @children
        }
    }
}
