import { TreeView } from "treeview.slint";
import { Constants, TreeViewItemData } from "../api.slint";

export component TreeItemPickerPopup inherits PopupWindow {
    in property <[TreeViewItemData]> model;
    in property <color> icons-color: transparent;  // Not colorized by default

    callback item-picked(index: int, item: TreeViewItemData);

    Rectangle {
        background: #00000050;

        Rectangle {
            width: min(0.8 * parent.width, 500px);
            height: min(self.preferred-height, 0.8 * parent.height);
            background: #000000;
            border-radius: 15px;
            border-width: 1px;
            border-color: Constants.librepcb-color;

            VerticalLayout {
                padding: 15px;

                view := TreeView {
                    model: model;
                    supports-expand: false;
                    icons-color: icons-color;

                    item-selected(idx, item) => {
                        item-picked(idx, item);
                    }
                }
            }
        }
    }
}
