import {
    ComboBox,
    IconButton,
    LengthEdit,
} from "../../widgets.slint";
import {
    Data,
    SchematicTabData,
    WindowSectionData,
} from "../../api.slint";

export component DrawPolygonToolBar inherits HorizontalLayout {
    in property <int> section-index;
    in-out property <WindowSectionData> section;
    property <[SchematicTabData]> tabs: section.schematic-tabs;

    spacing: 2px;

    layer-cbx := ComboBox {
        model: tabs[section.current-tab-index].tool-layer.items;
        current-index: tabs[section.current-tab-index].tool-layer.current-index;

        current-index-changed(index) => {
            tabs[section.current-tab-index].tool-layer.current-index = index;
        }
    }

    line-width-edt := LengthEdit {
        data: tabs[section.current-tab-index].tool-line-width;
        icon: @image-url("../../../../bootstrap-icons/icons/border-width.svg");
        tooltip: @tr("Line Width");
        min-width-text: "1.234";

        value-changed(v) => {
            tabs[section.current-tab-index].tool-line-width.value = v;
        }

        unit-changed(u) => {
            tabs[section.current-tab-index].tool-line-width.unit = u;
        }

        increase-triggered => {
            tabs[section.current-tab-index].tool-line-width.increase = true;
        }

        decrease-triggered => {
            tabs[section.current-tab-index].tool-line-width.decrease = true;
        }
    }

    fill-sw := IconButton {
        width: line-width-edt.height;
        height: self.width;
        icon: @image-url("../../../../font-awesome/svgs/solid/fill-drip.svg");
        icon-scale: 0.6;
        tooltip: @tr("Fill Area");
        background-color: Data.theme.palette.control;
        background-color-hovered: Data.theme.palette.control-hovered;
        background-color-checked: Data.theme.palette.control-checked;
        border-color: Data.theme.palette.base-border;
        border-width: 1px;
        color-enabled: Data.theme.palette.control-text-muted;
        color-hovered: Data.theme.palette.base-text-hovered;
        color-checked: Data.theme.palette.base-text;
        checked: tabs[section.current-tab-index].tool-filled;

        clicked => {
            tabs[section.current-tab-index].tool-filled = !self.checked;
        }
    }
}
