import { ComboBox, LineEdit } from "std-widgets.slint";
import { LengthEdit } from "../../common/lengthedit.slint";

export component AddTextToolBar inherits HorizontalLayout {
    spacing: 5px;

    Text {
        vertical-alignment: center;
        text: @tr("Layer:");
    }

    ComboBox {
        model: ["Guide", "Schematic Frame"];
    }

    Text {
        vertical-alignment: center;
        text: @tr("Text:");
    }

    LineEdit {
        text: "{{PROJECT}}";
    }

    Text {
        vertical-alignment: center;
        text: @tr("Height:");
    }

    LengthEdit { }
}
