import { ComboBox, CheckBox } from "std-widgets.slint";
import { LengthEdit } from "../../common/lengthedit.slint";

export component DrawPolygonToolBar inherits HorizontalLayout {
    spacing: 5px;

    Text {
        vertical-alignment: center;
        text: @tr("Layer:");
    }

    ComboBox {
        model: ["Guide", "Schematic Frame"];
    }

    Text {
        vertical-alignment: center;
        text: @tr("Width:");
    }

    LengthEdit { }

    CheckBox {
        text: @tr("Fill");
    }
}
