import { ComboBox, CheckBox } from "std-widgets.slint";
import { WindowSectionData, SchematicTabData, SchematicTool } from "../../api/types.slint";
import { SceneButton } from "../../common/scenebutton.slint";
import { ToolButton } from "../../common/toolbutton.slint";
import { LengthEdit } from "../../common/lengthedit.slint";
import { DrawWireToolBar } from "./drawwiretoolbar.slint";
import { DrawPolygonToolBar } from "./drawpolygontoolbar.slint";
import { AddTextToolBar } from "./addtexttoolbar.slint";
import { AddComponentToolBar } from "./addcomponenttoolbar.slint";
import { Backend } from "../../api/backend.slint";
import { Data } from "../../api/data.slint";
import { ActionId } from "../../api/types.slint";
import { EditToolBar } from "../../edittoolbar.slint";

export component SchematicTab inherits Image {
    in property <int> section-index;
    in-out property <WindowSectionData> section;
    property <[SchematicTabData]> tabs: section.schematic-tabs;

    image-fit: ImageFit.preserve;
    image-rendering: ImageRendering.pixelated;
    source: Backend.render-scene(section-index, root.width, root.height, section.frame);

    if Data.preview-mode: Rectangle {
        background: white;
    }

    fs := FocusScope {
        enabled: false;
    }

    ta := TouchArea {
        mouse-cursor: tabs[section.current-tab-index].cursor;

        top-bar := Rectangle {
            y: 0;
            width: self.preferred-width;
            height: self.preferred-height;
            background: #505050;
            border-bottom-left-radius: self.height / 2;
            border-bottom-right-radius: self.height / 2;
            //opacity: (ta.has-hover || ta.pressed) ? 1 : 0.2;

            //animate opacity { duration: 100ms; }

            HorizontalLayout {
                alignment: center;
                padding-left: 15px;
                padding-right: 15px;
                padding-top: 2px;
                padding-bottom: 5px;

                if tabs[section.current-tab-index].active-tool == SchematicTool.wire: DrawWireToolBar {
                    section-index: section-index;
                    section: section;
                }

                if tabs[section.current-tab-index].active-tool == SchematicTool.polygon: DrawPolygonToolBar {
                    section-index: section-index;
                    section: section;
                }

                if tabs[section.current-tab-index].active-tool == SchematicTool.text: AddTextToolBar { }

                if tabs[section.current-tab-index].active-tool == SchematicTool.component: AddComponentToolBar { }
            }
        }

        /*EditToolBar {
            y: top-bar.y + top-bar.height + 10px;
            opacity: (ta.has-hover || ta.pressed) ? 1 : 0.2;

            animate opacity { duration: 100ms; }
        }*/

        VerticalLayout {
            x: 7px;
            y: 7px;
            width: self.preferred-width;
            spacing: 5px;

            ToolButton {
                image: @image-url("../../img/cursor.svg");
                tooltip: @tr("Select");
                status-tip: @tr("Select & modify existing objects");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.select;

                clicked => {
                    if Data.preview-mode {
                        tabs[section.current-tab-index].active-tool = SchematicTool.select;
                        return true; // Workaround for warning in generated header
                    } else {
                        Backend.action-triggered(ActionId.tool-select, section-index);
                    }
                }
            }

            ToolButton {
                image: @image-url("../../img/draw-wire.svg");
                tooltip: @tr("Draw Wires");
                status-tip: @tr("Draw wires to create electrical connections between symbol pins");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.wire;

                clicked => {
                    if Data.preview-mode {
                        tabs[section.current-tab-index].active-tool = SchematicTool.wire;
                        return true; // Workaround for warning in generated header
                    } else {
                        Backend.action-triggered(ActionId.tool-wire, section-index);
                    }
                }
            }

            ToolButton {
                image: @image-url("../../img/netlabel.svg");
                tooltip: @tr("Add Net Labels");
                status-tip: @tr("Add net labels to explicitly specify the net of wires");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.netlabel;

                clicked => {
                    if Data.preview-mode {
                        tabs[section.current-tab-index].active-tool = SchematicTool.netlabel;
                        return true; // Workaround for warning in generated header
                    } else {
                        Backend.action-triggered(ActionId.tool-netlabel, section-index);
                    }
                }
            }

            ToolButton {
                image: @image-url("../../img/draw-polygon.svg");
                tooltip: @tr("Draw Polygons");
                status-tip: @tr("Draw graphical (i.e. non-functional) polygons");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.polygon;

                clicked => {
                    if Data.preview-mode {
                        tabs[section.current-tab-index].active-tool = SchematicTool.polygon;
                        return true; // Workaround for warning in generated header
                    } else {
                        Backend.action-triggered(ActionId.tool-polygon, section-index);
                    }
                }
            }

            ToolButton {
                image: @image-url("../../img/draw-text.svg");
                tooltip: @tr("Add Text Labels");
                status-tip: @tr("Add graphical (i.e. non-functional) text labels");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.text;

                clicked => {
                    if Data.preview-mode {
                        tabs[section.current-tab-index].active-tool = SchematicTool.text;
                        return true; // Workaround for warning in generated header
                    } else {
                        Backend.action-triggered(ActionId.tool-text, section-index);
                    }
                }
            }

            ToolButton {
                image: @image-url("../../img/plus.svg");
                tooltip: @tr("Place Components");
                status-tip: @tr("Insert components from the workspace libraries");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.component;

                clicked => {
                    if Data.preview-mode {
                        tabs[section.current-tab-index].active-tool = SchematicTool.component;
                        return true; // Workaround for warning in generated header
                    } else {
                        Backend.action-triggered(ActionId.tool-component, section-index);
                    }
                }
            }

            ToolButton {
                image: @image-url("../../img/ruler.svg");
                tooltip: @tr("Measure");
                status-tip: @tr("Measure the distance between two points");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.measure;

                clicked => {
                    if Data.preview-mode {
                        tabs[section.current-tab-index].active-tool = SchematicTool.measure;
                        return true; // Workaround for warning in generated header
                    } else {
                        Backend.action-triggered(ActionId.tool-measure, section-index);
                    }
                }
            }
        }

        VerticalLayout {
            x: parent.width - self.preferred-width - 7px;
            y: 7px;
            width: self.preferred-width;
            spacing: 5px;

            SceneButton {
                image: @image-url("../../img/zoom-fit.svg");
                bg-color: tabs[section.current-tab-index].background-color;
                fg-color: tabs[section.current-tab-index].overlay-color;
                clicked => {
                    Backend.scene-zoom-fit-clicked(section-index, root.width, root.height);
                }
            }

            SceneButton {
                image: @image-url("../../img/zoom-in.svg");
                bg-color: tabs[section.current-tab-index].background-color;
                fg-color: tabs[section.current-tab-index].overlay-color;
                clicked => {
                    Backend.scene-zoom-in-clicked(section-index, root.width, root.height);
                }
            }

            SceneButton {
                image: @image-url("../../img/zoom-out.svg");
                bg-color: tabs[section.current-tab-index].background-color;
                fg-color: tabs[section.current-tab-index].overlay-color;
                clicked => {
                    Backend.scene-zoom-out-clicked(section-index, root.width, root.height);
                }
            }

            SceneButton {
                text: "pins";
                font-size: 10px;
                bg-color: tabs[section.current-tab-index].background-color;
                fg-color: tabs[section.current-tab-index].overlay-color;
                checkable: true;
                checked: tabs[section.current-tab-index].show-pin-numbers;

                changed checked => {
                    tabs[section.current-tab-index].show-pin-numbers = self.checked;
                }
            }
        }

        pointer-event(e) => {
            if (e.kind == PointerEventKind.down) {
                Data.section-clicked(section-index);
                if (!fs.has-focus) {
                    fs.focus();
                }
            }
            return Backend.scene-pointer-event(section-index, self.mouse-x, self.mouse-y, self.absolute-position, e);
        }

        scroll-event(e) => {
            return Backend.scene-scrolled(section-index, self.mouse-x, self.mouse-y, e);
        }
    }
}
