import { ComboBox, CheckBox } from "std-widgets.slint";
import { WindowSection, SchematicTabData, SchematicTool } from "../../api/types.slint";
import { SceneButton } from "../../common/scenebutton.slint";
import { ToolButton } from "../../common/toolbutton.slint";
import { LengthEdit } from "../../common/lengthedit.slint";
import { DrawWireToolBar } from "./drawwiretoolbar.slint";
import { DrawPolygonToolBar } from "./drawpolygontoolbar.slint";
import { AddTextToolBar } from "./addtexttoolbar.slint";
import { AddComponentToolBar } from "./addcomponenttoolbar.slint";
import { Backend } from "../../api/backend.slint";
import { Data } from "../../api/data.slint";
import { EditToolBar } from "../../edittoolbar.slint";

export component SchematicTab inherits Image {
    in property <int> section-index;
    in-out property <WindowSection> section;
    property <[SchematicTabData]> tabs: section.schematic-tabs;

    image-fit: ImageFit.preserve;
    image-rendering: ImageRendering.pixelated;
    source: Backend.render-scene(section-index, root.width, root.height, section.frame);

    if Data.preview-mode: Rectangle {
        background: white;
    }

    fs := FocusScope {
        enabled: false;
    }

    ta := TouchArea {
        top-bar := Rectangle {
            y: 0;
            width: self.preferred-width;
            height: self.preferred-height;
            background: #505050;
            border-bottom-left-radius: self.height / 2;
            border-bottom-right-radius: self.height / 2;
            //opacity: (ta.has-hover || ta.pressed) ? 1 : 0.2;

            //animate opacity { duration: 100ms; }

            HorizontalLayout {
                alignment: center;
                padding-left: 15px;
                padding-right: 15px;
                padding-top: 2px;
                padding-bottom: 5px;

                if tabs[section.current-tab-index].active-tool == SchematicTool.draw-wire: DrawWireToolBar { }

                if tabs[section.current-tab-index].active-tool == SchematicTool.draw-polygon: DrawPolygonToolBar { }

                if tabs[section.current-tab-index].active-tool == SchematicTool.add-text: AddTextToolBar { }

                if tabs[section.current-tab-index].active-tool == SchematicTool.add-component: AddComponentToolBar { }
            }
        }

        /*EditToolBar {
            y: top-bar.y + top-bar.height + 10px;
            opacity: (ta.has-hover || ta.pressed) ? 1 : 0.2;

            animate opacity { duration: 100ms; }
        }*/

        VerticalLayout {
            x: 7px;
            y: 7px;
            width: self.preferred-width;
            spacing: 5px;

            ToolButton {
                image: @image-url("../../img/cursor.svg");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.select;

                clicked => {
                    tabs[section.current-tab-index].active-tool = SchematicTool.select;
                }
            }

            ToolButton {
                image: @image-url("../../img/draw-wire.svg");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.draw-wire;

                clicked => {
                    tabs[section.current-tab-index].active-tool = SchematicTool.draw-wire;
                }
            }

            ToolButton {
                image: @image-url("../../img/netlabel.svg");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.add-netlabel;

                clicked => {
                    tabs[section.current-tab-index].active-tool = SchematicTool.add-netlabel;
                }
            }

            ToolButton {
                image: @image-url("../../img/draw-polygon.svg");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.draw-polygon;

                clicked => {
                    tabs[section.current-tab-index].active-tool = SchematicTool.draw-polygon;
                }
            }

            ToolButton {
                image: @image-url("../../img/draw-text.svg");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.add-text;

                clicked => {
                    tabs[section.current-tab-index].active-tool = SchematicTool.add-text;
                }
            }

            ToolButton {
                image: @image-url("../../img/plus.svg");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.add-component;

                clicked => {
                    tabs[section.current-tab-index].active-tool = SchematicTool.add-component;
                }
            }

            ToolButton {
                image: @image-url("../../img/ruler.svg");
                checked: tabs[section.current-tab-index].active-tool == SchematicTool.measure;

                clicked => {
                    tabs[section.current-tab-index].active-tool = SchematicTool.measure;
                }
            }
        }

        VerticalLayout {
            x: parent.width - self.preferred-width - 7px;
            y: 7px;
            width: self.preferred-width;
            spacing: 5px;

            SceneButton {
                image: @image-url("../../img/zoom-fit.svg");
                bg-color: tabs[section.current-tab-index].background-color;
                fg-color: tabs[section.current-tab-index].overlay-color;
                clicked => {
                    Backend.scene-zoom-fit-clicked(section-index, root.width, root.height);
                }
            }

            SceneButton {
                image: @image-url("../../img/zoom-in.svg");
                bg-color: tabs[section.current-tab-index].background-color;
                fg-color: tabs[section.current-tab-index].overlay-color;
                clicked => {
                    Backend.scene-zoom-in-clicked(section-index, root.width, root.height);
                }
            }

            SceneButton {
                image: @image-url("../../img/zoom-out.svg");
                bg-color: tabs[section.current-tab-index].background-color;
                fg-color: tabs[section.current-tab-index].overlay-color;
                clicked => {
                    Backend.scene-zoom-out-clicked(section-index, root.width, root.height);
                }
            }

            SceneButton {
                text: "pins";
                font-size: 10px;
                bg-color: tabs[section.current-tab-index].background-color;
                fg-color: tabs[section.current-tab-index].overlay-color;
                checkable: true;
                checked: tabs[section.current-tab-index].show-pin-numbers;

                changed checked => {
                    tabs[section.current-tab-index].show-pin-numbers = self.checked;
                }
            }
        }

        pointer-event(e) => {
            if (e.kind == PointerEventKind.down) {
                fs.focus();
            }
            return Backend.scene-pointer-event(section-index, self.mouse-x, self.mouse-y, self.absolute-position, e);
        }

        scroll-event(e) => {
            return Backend.scene-scrolled(section-index, self.mouse-x, self.mouse-y, e);
        }
    }
}
