import {
    Button,
    CheckBox,
    IconButton,
    LinkText,
    PanelHeader,
    ProgressBar,
} from "../widgets.slint";
import {
    Backend,
    Data,
    ProjectAction,
    ProjectData,
} from "../api.slint";

export component OrderPanel inherits Rectangle {
    property <int> project-index: Data.current-project-index;
    property <ProjectData> project: Data.projects[project-index];
    property <bool> available: project.boards.length > 0;
    property <bool> info-error: project.valid && project.order-info-url.is-empty && (!project.order-status.is-empty);
    property <bool> ready: project.valid && (!project.order-info-url.is-empty);
    property <bool> uploading: project.valid && project.order-upload-progress >= 0;
    property <bool> clicked: false;

    background: #2a2a2a;

    // Request updating API status information.
    function request-info() {
        if available {
            Backend.trigger-project(project-index, ProjectAction.prepare-order);
        }
    }

    init => {
        request-info();

        // Set focus when panel is shown. Not sure if it's always desired(?).
        fs.focus();
    }

    changed project-index => {
        request-info();
    }

    fs := FocusScope {
        VerticalLayout {
            header := PanelHeader {
                z: 10;  // For the tooltip.
                title: @tr("Order {}", project.name);
                highlight: fs.has-focus;
                show-spinner: available && (!info-error) && (!ready);

                if info-error: error-btn := IconButton {
                    width: self.height;
                    style: read-only;
                    icon: @image-url("../../../../font-awesome/svgs/solid/triangle-exclamation.svg");
                    icon-scale: 0.7;
                    color-disabled: yellow;
                    enabled: false;
                    accessible-role: none;
                }
            }

            VerticalLayout {
                padding: 8px;
                spacing: 10px;
                vertical-stretch: 1;
                alignment: start;

                Text {
                    wrap: word-wrap;
                    text: @tr("Finished the PCB design? Let it manufacture by one of our fabrication partners - easy, safe and fast!");
                }

                open-browser-sw := CheckBox {
                    text: @tr("Open web browser after upload");
                    checked: Data.order-pcb-open-web-browser;
                    enabled: ready && (!uploading) && ((!clicked) || project.order-upload-url.is-empty);

                    toggled(checked) => {
                        Data.order-pcb-open-web-browser = checked;
                    }
                }

                upload-btn := Button {
                    primary: true;
                    enabled: ready && (!uploading) && ((!clicked) || project.order-upload-url.is-empty);
                    text: @tr("Upload Project");

                    clicked => {
                        clicked = true;
                        if open-browser-sw.checked {
                            Backend.trigger-project(project-index, ProjectAction.start-order-and-open);
                        } else {
                            Backend.trigger-project(project-index, ProjectAction.start-order);
                        }
                    }
                }

                if uploading: progress-bar := ProgressBar {
                    progress: project.order-upload-progress / 100;
                }

                VerticalLayout {
                    spacing: 3px;

                    status-txt := TextInput {
                        font-italic: true;
                        read-only: true;
                        single-line: false;
                        wrap: word-wrap;
                        text: {
                            if !available {
                                @tr("This project does not contain any board, so there's nothing you could order.")
                            } else if !project.order-status.is-empty {
                                project.order-status
                            } else if project.order-info-url.is-empty {
                                @tr("Checking availability") + "..."
                            } else {
                                ""
                            }
                        };
                    }

                    if !project.order-upload-url.is-empty: upload-url-btn := LinkText {
                        text: project.order-upload-url;
                        status-tip: self.text;
                        overflow: elide;

                        clicked => {
                            Backend.open-url(self.text);
                        }
                    }
                }
            }

            PanelHeader {
                title: @tr("Details");
            }

            VerticalLayout {
                padding: 8px;
                spacing: 8px;

                Text {
                    wrap: word-wrap;
                    font-italic: true;
                    font-size: 11.5px;
                    text: @tr("This tool helps you to quickly and easily get your designed PCB manufactured. The project directory will be exported to a *.lppz archive and uploaded to the API server configured in your workspace settings. Afterwards you can continue the order process in the web browser, e.g. to choose the preferred manufacturing partner. Just try it!");
                }
            }

            if ready: PanelHeader {
                title: @tr("Privacy Policy");
            }

            if ready: VerticalLayout {
                padding: 8px;
                spacing: 8px;

                Text {
                    wrap: word-wrap;
                    font-italic: true;
                    font-size: 11px;
                    text: @tr("Privacy and transparency are important to us. Details about how this feature works behind the scenes are available here:");
                }

                LinkText {
                    font-size: 11px;
                    overflow: elide;
                    text: project.order-info-url;
                    status-tip: self.text;
                }
            }
        }
    }
}
