import { ToolTip } from "./tooltip.slint";
import { Data } from "../api/data.slint";

export component ToolButton inherits Rectangle {
    in property <string> tooltip;
    in property <string> status-tip;
    in property <bool> checked: false;
    in property <image> image;

    callback clicked <=> ta.clicked;

    width: 30px;
    height: 30px;
    background: (checked || ta.pressed) ? blue : (ta.has-hover ? #606060 : #303030);
    border-radius: 3px;

    Image {
        width: parent.width * 0.7;
        height: self.width;
        image-fit: contain;
        colorize: white;
        source: image;
    }

    ta := TouchArea {
        changed has-hover => {
            if !root.status-tip.is-empty {
                if self.has-hover {
                    Data.current-status-tip = root.status-tip;
                } else {
                    Data.current-status-tip = "";
                }
            }
        }
    }

    if ta.has-hover: ToolTip {
        x: parent.width + 5px;
        y: (parent.height - self.height) / 2;
        text: tooltip;
    }
}
