import { Globals, WindowSection, Tab, ActionId, Board2dTabData } from "../globals.slint";
import { SceneButton } from "../scenebutton.slint";

export component Board2dTab inherits Image {
    in property <int> section-index;
    in-out property <WindowSection> section;
    property <[Board2dTabData]> tabs: section.board-2d-tabs;

    image-fit: ImageFit.preserve;
    image-rendering: ImageRendering.pixelated;
    source: Globals.render-scene(section-index, root.width, root.height, section.frame);

    TouchArea {
        pointer-event(e) => {
            return Globals.scene-pointer-event(section-index, self.mouse-x, self.mouse-y, self.absolute-position, e);
        }

        scroll-event(e) => {
            return Globals.scene-scrolled(section-index, self.mouse-x, self.mouse-y, e);
        }
    }

    VerticalLayout {
        x: parent.width - self.preferred-width - 10px;
        y: 10px;
        width: self.preferred-width;
        spacing: 5px;

        SceneButton {
            image: @image-url("../img/zoom-fit.svg");
            bg-color: tabs[section.current-tab-index].background-color;
            fg-color: tabs[section.current-tab-index].overlay-color;
            clicked => {
                Globals.scene-zoom-fit-clicked(section-index, root.width, root.height);
            }
        }

        SceneButton {
            image: @image-url("../img/zoom-in.svg");
            bg-color: tabs[section.current-tab-index].background-color;
            fg-color: tabs[section.current-tab-index].overlay-color;
            clicked => {
                Globals.scene-zoom-in-clicked(section-index, root.width, root.height);
            }
        }

        SceneButton {
            image: @image-url("../img/zoom-out.svg");
            bg-color: tabs[section.current-tab-index].background-color;
            fg-color: tabs[section.current-tab-index].overlay-color;
            clicked => {
                Globals.scene-zoom-out-clicked(section-index, root.width, root.height);
            }
        }

        SceneButton {
            text: "3D";
            bg-color: tabs[section.current-tab-index].background-color;
            fg-color: tabs[section.current-tab-index].overlay-color;
            clicked => {
                Globals.action-triggered(ActionId.board-2d-tab-open-3d, section-index);
            }
        }
    }
}
