import { WindowSection, Tab, Board3dTabData } from "../types.slint";
import { SceneButton } from "../scenebutton.slint";
import { Callbacks } from "../callbacks.slint";

export component Board3dTab inherits Image {
    in property <int> section-index;
    in-out property <WindowSection> section;
    property <[Board3dTabData]> tabs: section.board-3d-tabs;

    image-fit: ImageFit.preserve;
    image-rendering: ImageRendering.pixelated;
    source: Callbacks.render-scene(section-index, root.width, root.height, section.frame);

    TouchArea {
        pointer-event(e) => {
            return Callbacks.scene-pointer-event(section-index, self.mouse-x, self.mouse-y, self.absolute-position, e);
        }

        scroll-event(e) => {
            return Callbacks.scene-scrolled(section-index, self.mouse-x, self.mouse-y, e);
        }
    }

    VerticalLayout {
        x: parent.width - self.preferred-width - 10px;
        y: 10px;
        width: self.preferred-width;
        spacing: 5px;

        SceneButton {
            image: @image-url("../img/zoom-fit.svg");
            bg-color: tabs[section.current-tab-index].background-color;
            fg-color: tabs[section.current-tab-index].overlay-color;
            clicked => {
                Callbacks.scene-zoom-fit-clicked(section-index, root.width, root.height);
            }
        }

        SceneButton {
            image: @image-url("../img/zoom-in.svg");
            bg-color: tabs[section.current-tab-index].background-color;
            fg-color: tabs[section.current-tab-index].overlay-color;
            clicked => {
                Callbacks.scene-zoom-in-clicked(section-index, root.width, root.height);
            }
        }

        SceneButton {
            image: @image-url("../img/zoom-out.svg");
            bg-color: tabs[section.current-tab-index].background-color;
            fg-color: tabs[section.current-tab-index].overlay-color;
            clicked => {
                Callbacks.scene-zoom-out-clicked(section-index, root.width, root.height);
            }
        }
    }
}
