import { PanelHeader } from "../common/panelheader.slint";
import { Data } from "../api/data.slint";
import { Backend } from "../api/backend.slint";
import { ProjectData } from "../api/types.slint";

component ProjectItem inherits Rectangle {
    in property <string> text <=> t-title.text;

    callback clicked <=> ta.clicked;

    background: ta.has-hover ? #404040 : transparent;

    HorizontalLayout {
        padding: 2px;
        padding-left: 12px;
        padding-right: 5px;

        t-title := Text { }
    }

    ta := TouchArea { }
}

export component ProjectPanel inherits Rectangle {
    property <ProjectData> project: Data.projects[Data.current-project-index];

    background: #2a2a2a;

    VerticalLayout {
        alignment: LayoutAlignment.start;

        PanelHeader {
            title: project.name;
        }

        PanelHeader {
            title: @tr("SCHEMATICS");
        }

        for schematic[index] in project.schematics: ProjectItem {
            text: schematic;

            clicked => {
                Backend.schematic-clicked(index);
            }
        }

        PanelHeader {
            title: @tr("BOARDS");
        }

        for board[index] in project.boards: ProjectItem {
            text: board;

            clicked => {
                Backend.board-clicked(index);
            }
        }
    }
}
