<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<project version="0">
    <meta>
        <name>Demo Brushless Controller Project</name>
        <author>U. Bruhin</author>
        <created>2013-04-13T12:43:52Z</created>
        <last_modified>2015-06-21T12:53:56Z</last_modified>
    </meta>
    <schematics>
        <schematic>main.xml</schematic>
    </schematics>
    <boards>
        <board>default.xml</board>
    </boards>
</project>
