import { LineEdit, VerticalBox } from "std-widgets.slint";
import { Int64, EditParseResult, LengthUnit } from "../api/types.slint";
import { Backend } from "../api/backend.slint";
import { Data } from "../api/data.slint";

export component UpDownButton inherits Rectangle {
    in property <string> text <=> t-title.text;

    width: 15px;
    background: black;

    t-title := Text {
        font-size: ta.has-hover ? 12px : 8px;
        color: ta.has-hover ? white : #cccccc;
    }

    ta := TouchArea {
        mouse-cursor: MouseCursor.pointer;
    }
}

export component UnitMenuItem {
    in property <LengthUnit> unit;

    callback clicked <=> ta.clicked;

    t-title := Text {
        font-size: 12px;
        color: ta.has-hover ? white : #cccccc;
        text: Data.get-unit-short-str(unit);
    }

    ta := TouchArea {
        mouse-cursor: MouseCursor.pointer;
    }
}

export component LengthEdit inherits Rectangle {
    in-out property <Int64> value;
    in-out property <LengthUnit> unit: LengthUnit.millimeters;
    property <EditParseResult> parse-result;

    width: 145px;
    preferred-height: 27px;
    forward-focus: le-text;

    le-text := LineEdit {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;
        font-size: 13px;

        init => {
            self.text = Backend.format-length(root.value, root.unit);
            parse-result.valid = true;
        }

        edited(s) => {
            parse-result = Backend.parse-length-input(s, unit);
            if (parse-result.valid) {
                value = parse-result.evaluated-value;
                unit = parse-result.evaluated-unit;
            }
        }

        accepted(s) => {
            self.text = Backend.format-length(root.value, root.unit);
            parse-result.evaluated-value = value;
            parse-result.evaluated-unit = unit;
            parse-result.valid = true;
            self.clear-focus();
        }
    }

    btn-up := UpDownButton {
        x: r-unit.x - self.width;
        y: 1px;
        height: (parent.height - 2px) / 2;
        text: "▲";
    }

    btn-down := UpDownButton {
        x: r-unit.x - self.width;
        y: parent.height / 2;
        height: (parent.height - 2px) / 2;
        text: "▼";
    }

    r-unit := Rectangle {
        x: parent.width - self.width;
        y: 1px;
        width: lblText.preferred-width + 10px;
        height: parent.height - 2px;
        background: black;
        border-top-right-radius: 8px;
        border-bottom-right-radius: 8px;

        lblText := Text {
            vertical-alignment: TextVerticalAlignment.center;
            color: touch.has-hover ? white : #cccccc;
            text: Data.get-unit-short-str(root.unit);
        }

        popup := PopupWindow {
            x: 0;
            y: parent.height + 2px;
            width: r-unit.width;
            Rectangle {
                background: black;
                border-radius: 8px;
                VerticalBox {
                    padding-left: 5px;
                    padding-right: 5px;
                    UnitMenuItem {
                        unit: LengthUnit.millimeters;
                        clicked(v) => {
                            root.unit = self.unit;
                        }
                    }

                    UnitMenuItem {
                        unit: LengthUnit.micrometers;
                        clicked(v) => {
                            root.unit = self.unit;
                        }
                    }

                    UnitMenuItem {
                        unit: LengthUnit.nanometers;
                        clicked(v) => {
                            root.unit = self.unit;
                        }
                    }

                    UnitMenuItem {
                        unit: LengthUnit.inches;
                        clicked(v) => {
                            root.unit = self.unit;
                        }
                    }

                    UnitMenuItem {
                        unit: LengthUnit.mils;
                        clicked(v) => {
                            root.unit = self.unit;
                        }
                    }
                }
            }
        }

        touch := TouchArea {
            mouse-cursor: MouseCursor.pointer;
            clicked => {
                popup.show();
            }
        }
    }

    Rectangle {
        x: r-unit.x;
        y: 6px;
        width: 1px;
        height: parent.height - 12px;
        background: gray;
    }

    if !parse-result.valid: Rectangle {
        x: -1px;
        y: -1px;
        width: parent.width + 2px;
        height: parent.height + 2px;
        border-width: 1px;
        border-radius: 10px;
        border-color: #ff0000;
    }
}
