import { ActionId } from "../api/types.slint";
import { Backend } from "../api/backend.slint";
import { Data } from "../api/data.slint";
import { Palette } from "std-widgets.slint";

export component MenuItem inherits Rectangle {
    in property <string> text <=> t-title.text;
    in property <string> status-tip;
    in property <image> icon <=> i-icon.source;

    callback clicked <=> ta.clicked;

    background: ta.has-hover ? #505050 : #353535;

    HorizontalLayout {
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 5px;
        padding-bottom: 5px;
        spacing: 5px;

        i-icon := Image {
            width: self.height;
            height: t-title.preferred-height;
            colorize: Palette.foreground;
        }

        t-title := Text {
            vertical-alignment: center;
            font-size: 15px;
            color: #d0d0d0;
        }
    }

    ta := TouchArea {
        changed has-hover => {
            if (root.status-tip != "") {
                if (self.has-hover) {
                    Data.hovered-status-tip = root.status-tip;
                } else {
                    Data.hovered-status-tip = "";
                }
            }
        }
    }
}

export component Menu inherits PopupWindow {
    Rectangle {
        background: #353535;

        VerticalLayout {
            @children
        }
    }
}
