export component ToolTip inherits Rectangle {
    in property <string> text <=> t.text;

    width: min(t.preferred-width + 10px, 800px);
    height: t.height + 10px;
    background: #101010;
    border-radius: 5px;
    opacity: 0;

    animate opacity { duration: 150ms; }

    t := Text {
        x: 5px;
        width: parent.width - 2 * self.x;
        color: #eeeeee;
        horizontal-alignment: TextHorizontalAlignment.left;
        vertical-alignment: TextVerticalAlignment.center;
        wrap: word-wrap;
        font-size: 14px;
    }

    init => {
        self.opacity = 1;
    }
}
