import { Action, Int64, EditParseResult, LengthUnit } from "./types.slint";
import { Data } from "./data.slint";

// Note: The callback implementations are just for the live preview, they will
// be overridden by the backend in the real use-case.
export global Backend {
    // Trigger some action
    //
    // Parameters:
    //  1. Action to trigger
    //  2. Section index (pass -1 for things outside a window section)
    //
    // Return value:
    //  Whether the action was handled or not
    pure callback trigger(Action, int) -> bool;
    trigger(action, section) => {
        return true;
    }

    // A key has been pressed
    pure callback key-pressed(KeyEvent) -> EventResult;

    pure callback parse-length-input(string, LengthUnit) -> EditParseResult;

    pure callback format-length(Int64, LengthUnit) -> string;
    format-length => {
        return "123.456789";
    }

    // Generic callback to open an URL
    //
    // - URL
    pure callback open-url(string);

    // A schematic in the projects panel has been clicked
    //
    // - Project index
    // - Schematic index
    pure callback schematic-clicked(int, int);

    // A board in the projects panel has been clicked
    //
    // - Project index
    // - Board index
    pure callback board-clicked(int, int);

    // Requested to switch to a particular tab
    //
    // - Section index
    // - Tab index
    pure callback tab-clicked(int, int);

    // Requested to close a particular tab
    //
    // - Section index
    // - Tab index
    pure callback tab-close-clicked(int, int);

    // Open a library
    //
    // - Library ID (see Library::id)
    pure callback open-library(string);

    // Uninstall a library
    //
    // - Library ID (see Library::id)
    pure callback uninstall-library(string);

    // Toggle checked state of all libraries
    //
    // - Check state
    pure callback toggle-libraries-checked(bool);

    // Clear libraries list filter term
    pure callback libraries-clear-filter();

    // Key event on the libraries list
    //
    // - Key event
    pure callback libraries-key-event(KeyEvent) -> EventResult;

    // Render a graphics scene image
    //
    // - Section index
    // - Scene width
    // - Scene height
    // - Frame number (to be ignored)
    pure callback render-scene(int, length, length, int) -> image;

    // Scene pointer event
    //
    // - Section index
    // - Cursor position X (relative to scene)
    // - Cursor position Y (relative to scene)
    // - Scene location within window
    // - Pointer event
    pure callback scene-pointer-event(int, length, length, Point, PointerEvent) -> EventResult;

    // Scene scrolled event
    //
    // - Section index
    // - Cursor position X (relative to scene)
    // - Cursor position Y (relative to scene)
    // - Scroll event
    pure callback scene-scrolled(int, length, length, PointerScrollEvent) -> EventResult;

    // Scene key pressed event
    //
    // - Section index
    // - Key event
    pure callback scene-key-pressed(int, KeyEvent) -> EventResult;

    // Scene key released event
    //
    // - Section index
    // - Key event
    pure callback scene-key-released(int, KeyEvent) -> EventResult;

    // Scene button "zoom to fit content" clicked
    //
    // - Section index
    // - Scene width
    // - Scene height
    pure callback scene-zoom-fit-clicked(int, length, length);

    // Scene button "zoom in" clicked
    //
    // - Section index
    // - Scene width
    // - Scene height
    pure callback scene-zoom-in-clicked(int, length, length);

    // Scene button "zoom out" clicked
    //
    // - Section index
    // - Scene width
    // - Scene height
    pure callback scene-zoom-out-clicked(int, length, length);

    // Request generating the preview of a project (e.g. its README.md)
    //
    // Lets the backend building the preview asynchronously, and updating the
    // following data members accordingly:
    //  - Data.project-preview-rendering
    //  - Data.project-preview-image
    //
    // Parameters:
    //  1. Absolute project file path (e.g. from TreeViewItemData::user-data)
    //  2. Width of the preview component
    //
    // Return value:
    //  Dummy (discarded), just to allow declarative, automatic re-evaluation
    pure callback request-project-preview(string, length) -> bool;
    request-project-preview(path, width) => {
        debug("Request project preview:", path, width);
        true
    }

    // Copy a string into the clipboard
    //
    // Parameters:
    //  1. String to copy
    //
    // Return value:
    //  True on success, false on failure
    pure callback copy-to-clipboard(string) -> bool;
    copy-to-clipboard(s) => {
        Data.preview-mode  // Make it fail if callback not bound in backend.
    }

    // Convert a string to uppercase
    //
    // Parameters:
    //  1. Input string
    //
    // Return value:
    //  Uppercase string
    pure callback to-upper(string) -> string;
    to-upper(s) => {
        // Just for the preview, convert the untranslated source strings.
        if !Data.preview-mode {
            "⚠"
        } else if s == "Quick Access" {
            "QUICK ACCESS"
        } else if s == "Workspace Projects" {
            "WORKSPACE PROJECTS"
        } else {
            s
        }
    }
}
