export global Constants {
    out property <color> librepcb-color: #29d682;

    out property <string> donate-url: "https://librepcb.org/donate/";
    out property <string> no-device-found-url: "https://librepcb.org/faq/#error-no-dev-or-pkg-found";
    out property <string> sources-url: "https://github.com/LibrePCB/LibrePCB";
    out property <string> support-url: "https://librepcb.org/help/";
    out property <string> user-manual-create-local-library-url: "https://librepcb.org/docs/quickstart/create-local-library/";
    out property <string> user-manual-create-board-url: "https://librepcb.org/docs/quickstart/create-project/board/";
    out property <string> user-manual-create-schematics-url: "https://librepcb.org/docs/quickstart/create-project/schematics/";
    out property <string> user-manual-url: "https://librepcb.org/docs/";
    out property <string> video-tutorials-url: "https://www.youtube.com/@LibrePCB";
    out property <string> website-url: "https://librepcb.org";
    out property <string> where-is-library-element-url: "https://librepcb.org/faq/#where-is-library-element";
}
