export global Constants {
    out property <color> librepcb-color: #29d682;

    out property <string> donate-url: "https://librepcb.org/donate/";
    out property <string> sources-url: "https://github.com/LibrePCB/LibrePCB";
    out property <string> support-url: "https://librepcb.org/help/";
    out property <string> user-manual-url: "https://librepcb.org/docs/";
    out property <string> video-tutorials-url: "https://www.youtube.com/@LibrePCB";
    out property <string> website-url: "https://librepcb.org";
}
