import {
    Board2dTabData,
    EditorTool,
    TreeViewItemData,
    GridStyle,
    LengthUnit,
    LibraryData,
    LibraryState,
    LibraryType,
    NotificationData,
    NotificationType,
    PanelPage,
    ProjectData,
    RuleCheckState,
    SchematicTabData,
    TabData,
    TabType,
    WindowSectionData
} from "types.slint";

export global Data {
    // Preview mode: True for preview, set to false by the backend
    in property <bool> preview-mode: true;

    // Window title
    in property <string> window-title: "LibrePCB 1.2.0-unstable";

    // Detailed app version information etc.
    in property <string> about-librepcb-details: "LibrePCB Version: 1.2.0\nGit Revision:     f079fa97b\nBuild Date:       2024-12-02T19:12:08\nQt Version:       6.2.4 (built against 6.2.4)\nCPU Architecture: x86_64\nOperating System: Ubuntu Core 22\nPlatform Plugin:  xcb\nTLS Library:      OpenSSL 3.0.2 15 Mar 2022\nOCC Library:      OCCT 7.7.2\nRuntime:          Snap";

    // Current side panel page
    in-out property <PanelPage> panel-page: PanelPage.home;

    // Static status bar message
    in property <string> status-bar-message;

    // Temporary status tip when hovering interactive UI elements
    in property <string> status-tip;

    // Workspace: Folder path
    in property <string> workspace-path: "/path/to/workspace";

    // Workspace: Folder tree
    in property <[TreeViewItemData]> workspace-folder-tree: [
        {
            icon: @image-url("../../../../../img/places/project_folder.png"),
            text: "folder-1",
            user-data: "folder-1",
            has-children: true,
            expanded: false,
        },
        {
            icon: @image-url("../../../../../img/places/project_folder.png"),
            text: "folder-2",
            user-data: "folder-2",
            is-project-file-or-folder: true,
            has-children: true,
            expanded: true,
        },
        {
            level: 1,
            icon: @image-url("../../../../../img/app/librepcb.svg"),
            text: "project-1.lpp",
            user-data: "project-1.lpp",
            is-project-file-or-folder: true,
            supports-pinning: true,
            pinned: true,
        },
        {
            level: 1,
            icon: @image-url("../../../../../img/app/librepcb.svg"),
            text: "project-2.lpp",
            user-data: "project-2.lpp",
            is-project-file-or-folder: true,
            supports-pinning: true,
            pinned: false,
        },
    ];

    // Quick access items
    in property <[TreeViewItemData]> quick-access-items: [
        {
            icon: @image-url("../../../../../img/app/librepcb.svg"),
            text: "project-1.lpp",
            hint: "foo/bar/project-1.lpp",
            user-data: "foo/bar/project-1.lpp",
            supports-pinning: true,
            pinned: false,
        },
        {
            icon: @image-url("../../../../../img/app/librepcb.svg"),
            text: "project-2.lpp",
            hint: "fooooooooooo/baaaaaaaaaaaaaaaaaaaaaaaar/project-2.lpp",
            user-data: "fooooooooooo/baaaaaaaaaaaaaaaaaaaaaaaar/project-2.lpp",
            supports-pinning: true,
            pinned: false,
        },
        {
            icon: @image-url("../../../../../img/app/librepcb.svg"),
            text: "project-3.lpp",
            hint: "foo/bar/project-3.lpp",
            user-data: "foo/bar/project-3.lpp",
            supports-pinning: true,
            pinned: true,
        },
    ];

    // Project preview: Project file path
    in-out property <string> project-preview-path;

    // Project preview: Rendering in progress
    in property <bool> project-preview-rendering: false;

    // Project preview: Preview image result
    in property <image> project-preview-image;

    // Notifications: Data model
    in property <[NotificationData]> notifications: [
        {
            type: NotificationType.tip,
            title: "Tip",
            description: "This is a tip notification",
            button-text: "Do Something",
            supports-dont-show-again: true,
            unread: true,
        },
        {
            type: NotificationType.info,
            title: "Info",
            description: "This is an info notification",
            unread: true,
        },
        {
            type: NotificationType.warning,
            title: "Warning",
            description: "This is a warning notification",
        },
        {
            type: NotificationType.critical,
            title: "Critical",
            description: "This is a critical notification",
        },
        {
            type: NotificationType.progress,
            title: "Progress",
            description: "This is a progress notification",
            progress: 50,
        },
    ];

    // Notifications: Unread messages count
    in property <int> notifications-unread: 2;

    // Notifications: Index of current progress notification (-1 if none)
    in property <int> notifications-progress-index: 4;

    // Notifications: Popup shown status
    in property <bool> notifications-shown: true;

    in property <string> order-info-url: "https://fab.librepcb.org/todo";

    in-out property <bool> ignore-placement-locks: true;

    in property <string> cursor-coordinates: "X: 123.456 Y: 123.456";

    in property <[ProjectData]> projects: [
        {
            valid: true,
            path: "/path/to/project-1.lpp",
            name: "Project 1",
            schematics: ["Power", "Logic"],
            boards: ["Default", "Experiment"],
        },
        {
            valid: true,
            path: "/path/to/project-2.lpp",
            name: "Project 2",
            schematics: ["Power", "Logic"],
            boards: ["Default", "Experiment"],
        },
    ];

    in-out property <int> current-project-index: 0;

    in property <bool> refreshing-available-libraries: false;

    in property <string> libraries-fetching-error: "Some error occurred.\nFoo bar...";

    in property <string> libraries-filter: "Foo";

    in property <int> outdated-libraries: 2;

    in property <int> checked-libraries: 3;

    in property <[LibraryData]> libraries: [
        {
            name: "My Library",
            description: "My own local library.",
            version: "v1.0",
            icon: @image-url("../../../../../img/library.png"),
            type: LibraryType.local,
            state: LibraryState.unknown,
        },
        {
            name: "LibrePCB Base",
            description: "Official LibrePCB Base Library",
            version: "v1.2.3",
            icon: @image-url("../../../../../img/app/librepcb.svg"),
            type: LibraryType.remote,
            state: LibraryState.up-to-date,
        },
        {
            name: "Microchip Technology / Atmel",
            description: "Integrated circuits and more (unofficial).",
            version: "v0.5",
            icon: @image-url("../../../../../img/app/librepcb.svg"),
            type: LibraryType.remote,
            state: LibraryState.outdated,
        },
        {
            name: "LibrePCB Integrated Circuits",
            description: "Official LibrePCB Integrated Circuits Library",
            icon: @image-url("../../../../../img/app/librepcb.svg"),
            type: LibraryType.online,
        },
        {
            name: "Microchip Technology / Atmel",
            description: "Integrated circuits and more (unofficial).",
            icon: @image-url("../../../../../img/app/librepcb.svg"),
            type: LibraryType.online,
            progress: 42,
        },
    ];

    in property <[WindowSectionData]> sections: [
        {
            tabs: [
                {
                    type: TabType.home,
                    project-index: -1,
                },
                {
                    type: TabType.create-library,
                    title: "Create Lib",
                    project-index: -1,
                },
                {
                    type: TabType.download-library,
                    title: "Download Lib",
                    project-index: -1,
                },
                {
                    type: TabType.schematic,
                    title: "Schematic",
                    project-index: 0,
                    rule-check-state: RuleCheckState.outdated,
                    rule-check-messages: [
                        {
                            severity: NotificationType.info,
                            message: "Hint message",
                            description: "Hint description.",
                            approved: false,
                            supports-autofix: true,
                        },
                        {
                            severity: NotificationType.warning,
                            message: "Warning message",
                            description: "Warning description.",
                            approved: true,
                            supports-autofix: false,
                        },
                        {
                            severity: NotificationType.critical,
                            message: "Error message",
                            description: "Error description.",
                            approved: false,
                            supports-autofix: true,
                        },
                    ],
                    rule-check-unapproved-messages: 42,
                    rule-check-execution-error: "",
                    can-save: true,
                    can-export-graphics: true,
                    can-undo: true,
                    can-redo: true,
                    can-cut: true,
                    can-copy: true,
                    can-paste: true,
                    can-remove: true,
                    can-rotate: true,
                    can-mirror: true,
                    can-move-align: true,
                    can-snap-to-grid: true,
                    can-reset-texts: true,
                    can-lock-placement: true,
                    can-edit-properties: true,
                },
                {
                    type: TabType.board-2d,
                    title: "Board",
                    project-index: 0,
                    can-save: true,
                    can-export-graphics: true,
                    can-undo: true,
                    can-redo: true,
                    can-cut: true,
                    can-copy: true,
                    can-paste: true,
                    can-remove: true,
                    can-rotate: true,
                    can-mirror: true,
                    can-move-align: true,
                    can-snap-to-grid: true,
                    can-reset-texts: true,
                    can-lock-placement: true,
                    can-edit-properties: true,
                },
            ],
            create-library-tabs: [
                { },
                {
                    name: "My Library",
                    name-error: "Name error",
                    description: "",
                    author: "",
                    author-default: "Me",
                    version: "",
                    version-default: "0.1",
                    version-error: "Version error",
                    url: "",
                    url-error: "URL error",
                    cc0: false,
                    directory: "",
                    directory-default: "My_Library.lplib",
                    directory-error: "Directory error",
                    valid: true,
                    creation-error: "Creation error",
                },
            ],
            download-library-tabs: [
                { },
                { },
                {
                    url: "",
                    url-error: "URL error",
                    url-suggestion: "https://example.com/library.zip",
                    directory: "",
                    directory-default: "My_Library.lplib",
                    directory-error: "Directory error",
                    valid: true,
                    download-running: true,
                    download-progress: 42,
                    download-error: "Download error",
                },
            ],
            schematic-tabs: [
                { },
                { },
                { },
                {
                    overlay-color: #dddddd78,
                    overlay-text-color: Colors.black,
                    grid-style: GridStyle.none,
                    grid-interval: "2.54",
                    unit: LengthUnit.millimeters,
                    show-pin-numbers: false,
                    tool: EditorTool.polygon,
                    tool-overlay-text: "X0:   123.4567 mm\nY0:   123.4567 mm\nX1:   123.4567 mm\nY1:   123.4567 mm\n\ndX:   123.4567 mm\ndY:   123.4567 mm\n\nL:    123.4567 mm\na:     90.0000 °",
                    tool-layer: {
                        items: ["Layer 1", "Layer 2", "Layer 3"],
                        current-index: 1,
                    },
                    tool-value: {
                        text: "{{PROJECT}}",
                        suggestions: ["{{Foo}}", "{{Bar}}"],
                    },
                    tool-attribute-value: {
                        enabled: true,
                        text: "42",
                        placeholder: "CAPACITANCE",
                    },
                    tool-attribute-unit: {
                        items: ["mV", "V", "kV"],
                        current-index: 1,
                    },
                },
            ],
            board-2d-tabs: [
                { },
                { },
                { },
                { },
                {
                    overlay-color: Colors.gray,
                    overlay-text-color: Colors.white,
                    grid-style: GridStyle.none,
                    grid-interval: "0.635",
                    unit: LengthUnit.millimeters,
                    tool: EditorTool.wire,
                    tool-overlay-text: "X0:   123.4567 mm\nY0:   123.4567 mm\nX1:   123.4567 mm\nY1:   123.4567 mm\n\ndX:   123.4567 mm\ndY:   123.4567 mm\n\nL:    123.4567 mm\na:     90.0000 °",
                    tool-net: {
                        items: ["Net 1", "Net 2", "Net 3"],
                        current-index: 1,
                    },
                    tool-layer: {
                        items: ["Layer 1", "Layer 2", "Layer 3"],
                        current-index: 1,
                    },
                    tool-value: {
                        text: "{{PROJECT}}",
                        suggestions: ["{{Foo}}", "{{Bar}}"],
                    },
                },
            ],
            current-tab-index: 3,
            highlight: true,
        },
        {
            tabs: [
                {
                    type: TabType.home,
                    project-index: -1,
                },
                {
                    type: TabType.board-3d,
                    title: "3D",
                    project-index: 1,
                    can-save: true,
                    can-undo: true,
                    can-redo: true,
                },
            ],
            current-tab-index: 1,
        },
    ];

    in-out property <int> current-section-index: 0;

    // Constant data
    out property <[LengthUnit]> all-length-units: [
        LengthUnit.millimeters,
        LengthUnit.micrometers,
        LengthUnit.nanometers,
        LengthUnit.inches,
        LengthUnit.mils,
    ];

    // Auto-calculated data
    in-out property <ProjectData> current-project: projects[current-project-index];
    in-out property <WindowSectionData> current-section: sections[current-section-index];
    in-out property <TabData> current-tab: current-section.tabs[current-section.current-tab-index];
    out property <bool> current-tab-is-2d: (current-tab.type == TabType.schematic) || (current-tab.type == TabType.board-2d);
    out property <bool> current-tab-is-2d-or-3d: (current-tab.type == TabType.schematic) || (current-tab.type == TabType.board-2d) || (current-tab.type == TabType.board-3d);
    in-out property <SchematicTabData> current-schematic-tab: current-section.schematic-tabs[current-section.current-tab-index];
    in-out property <Board2dTabData> current-board-2d-tab: current-section.board-2d-tabs[current-section.current-tab-index];
    out property <GridStyle> current-grid-style: (current-tab.type == TabType.schematic) ? current-schematic-tab.grid-style : current-board-2d-tab.grid-style;
    out property <string> current-grid-interval: (current-tab.type == TabType.schematic) ? current-schematic-tab.grid-interval : current-board-2d-tab.grid-interval;
    out property <LengthUnit> current-unit: (current-tab.type == TabType.schematic) ? current-schematic-tab.unit : current-board-2d-tab.unit;

    public function set-current-grid-style(gs: GridStyle) {
        if (current-tab.type == TabType.schematic) {
            current-section.schematic-tabs[current-section.current-tab-index].grid-style = gs;
        } else if (current-tab.type == TabType.board-2d) {
            current-section.board-2d-tabs[current-section.current-tab-index].grid-style = gs;
        } else {
            debug("Unhandled case in set-current-grid-style().");
        }
    }

    public function set-current-unit(u: LengthUnit) {
        if (current-tab.type == TabType.schematic) {
            current-section.schematic-tabs[current-section.current-tab-index].unit = u;
        } else if (current-tab.type == TabType.board-2d) {
            current-section.board-2d-tabs[current-section.current-tab-index].unit = u;
        } else {
            debug("Unhandled case in set-current-unit().");
        }
    }

    pure public function get-icon-for-tab-type(t: TabType) -> image {
        if (t == TabType.home) {
            return @image-url("../../../../bootstrap-icons/icons/house-fill.svg");
        } else if (t == TabType.create-library) {
            return @image-url("../../../../bootstrap-icons/icons/database-add.svg");
        } else if (t == TabType.download-library) {
            return @image-url("../../../../bootstrap-icons/icons/cloud-arrow-down-fill.svg");
        } else if (t == TabType.schematic) {
            return @image-url("../../../../font-awesome/svgs/regular/image.svg");
        } else if (t == TabType.board-2d) {
            return @image-url("../../../../bootstrap-icons/icons/motherboard.svg");
        } else if (t == TabType.board-3d) {
            return @image-url("../../../../bootstrap-icons/icons/badge-3d.svg");
        } else {
            debug("Unhandled case in get-icon-for-tab-type().");
            return @image-url("");
        }
    }

    public function section-clicked(index: int) {
        if (current-section-index != index) {
            current-section-index = index;
            if ((current-tab.project-index >= 0) && (current-tab.project-index < Data.projects.length)) {
                current-project-index = current-tab.project-index;
            }
        }
    }

    pure public function get-rule-check-title-for-tab-type(type: TabType) -> string {
        if (type == TabType.schematic) {
            return @tr("Electrical Rule Check (ERC)");
        } else if (type == TabType.board-2d) {
            return @tr("Design Rule Check (DRC)");
        } else {
            return "";
        }
    }
}
