// WARNING: This file is autogenerated by cbindgen, don't modify it manually.
// clang-format off

#pragma once

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
#define NONNULL

namespace librepcb {
namespace rs {
namespace spacemouse {

/**
 * USB vendor ID used by current 3Dconnexion devices.
 */
constexpr static const uint16_t VENDOR_ID_3DCONNEXION = 9583;

/**
 * Legacy USB vendor ID used by early (Logitech-era) 3Dconnexion devices.
 */
constexpr static const uint16_t VENDOR_ID_LOGITECH_3DCONNEXION = 1133;

/**
 * HID usage page identifying "Generic Desktop Controls".
 */
constexpr static const uint16_t USAGE_PAGE_GENERIC_DESKTOP = 1;

/**
 * HID usage ID identifying a "Multi-axis Controller" within the Generic
 * Desktop Controls usage page - the usage LibrePCB filters on, matching
 * what the previous Win32 Raw Input backend already did.
 */
constexpr static const uint16_t USAGE_ID_MULTI_AXIS_CONTROLLER = 8;

/**
 * Opaque handle exposed to C++, wrapping a [`SpaceMouseBackend`].
 */
struct FfiSpaceMouseBackend;

/**
 * Plain-old-data mirror of [`SpaceMouseMotion`] with a stable `#[repr(C)]`
 * layout for use across the FFI boundary.
 */
struct SpaceMouseMotionFfi {
  /**
   * Pan left(-)/right(+)
   */
  int16_t translation_x;
  /**
   * Pan away(-)/towards(+) the user
   */
  int16_t translation_y;
  /**
   * Pan/zoom down(-)/up(+)
   */
  int16_t translation_z;
  /**
   * Tilt (pitch)
   */
  int16_t rotation_x;
  /**
   * Tilt (yaw)
   */
  int16_t rotation_y;
  /**
   * Twist (roll)
   */
  int16_t rotation_z;
};

/**
 * C ABI callback invoked whenever the device reports new motion.
 *
 * <div class="warning">
 * Fires on a background thread owned by the Rust side, *not* the thread
 * that called [`ffi_spacemouse_backend_new`]. The C++ side is responsible
 * for hopping onto whatever thread it needs before touching anything not
 * safe to call from an arbitrary thread (e.g. before emitting a Qt
 * signal).  Also see `spacemouseinputrust.cpp`.
 * </div>
 */
using MotionCallback = void(*)(void *user_data, SpaceMouseMotionFfi motion);

/**
 * C ABI callback invoked whenever a compatible device is connected or
 * disconnected. Same threading caveat as [`MotionCallback`].
 */
using ConnectedCallback = void(*)(void *user_data, bool connected);

extern "C" {

/**
 * Create a new backend and start capturing device input in the background.
 *
 * `user_data` is passed back unmodified as the first argument of every
 * callback invocation; Rust never dereferences it. The caller must keep
 * whatever it points to alive until after
 * [`ffi_spacemouse_backend_free`] returns, and must not call back into
 * Rust synchronously from within a callback (there is no re-entrancy
 * protection).
 *
 * Never returns null: Unlike opening a specific device, constructing the
 * backend itself cannot fail - "no compatible device found (yet)" is not
 * an error, it's the normal state before `on_connected_changed(true)` is
 * ever invoked.
 */
FfiSpaceMouseBackend *ffi_spacemouse_backend_new(void *user_data,
                                                 MotionCallback on_motion,
                                                 ConnectedCallback on_connected_changed);

/**
 * Whether a compatible device is currently detected as connected.
 */
bool ffi_spacemouse_backend_is_connected(const FfiSpaceMouseBackend * NONNULL backend);

/**
 * Stop capturing, join the background thread, and free the backend.
 *
 * # Safety (from the C++ side)
 * `backend` must be a non-null pointer previously returned by
 * [`ffi_spacemouse_backend_new`] and not already freed.
 */
void ffi_spacemouse_backend_free(FfiSpaceMouseBackend *backend);

}  // extern "C"

}  // namespace spacemouse
}  // namespace rs
}  // namespace librepcb

// clang-format on
