jobs:
  - job: Windows
    pool:
      vmImage: 'windows-2019'
    timeoutInMinutes: 180
    container: librepcb/librepcb-dev:windowsservercore-ltsc2019-qt6.6-64bit-2
    variables:
      OS: 'windows'
      ARCH: 'x86_64'
      DEPLOY: true
    steps:
    - checkout: self
      clean: true
      submodules: recursive
    - bash: ./ci/print_environment.sh
      displayName: Print Environment
    - bash: ./ci/install_dependencies.sh
      displayName: Install Dependencies
    - template: azure-cache.yml
    - bash: ./ci/print_environment.sh
      displayName: Print New Environment  # Print again since it has been modified
    - bash: ./ci/build_librepcb.sh
      displayName: Build LibrePCB
    - bash: ./ci/build_windows_archive.sh
      displayName: Build Archive
      condition: and(succeeded(), eq(variables['DEPLOY'], 'true'))
    - bash: ./ci/build_windows_installer.sh
      displayName: Build Installer
      condition: and(succeeded(), eq(variables['DEPLOY'], 'true'))
    - script: cd libs\\librepcb\\rust-core && cargo test --features=fail-on-warnings
      displayName: Run rust-core tests
    - script: build\\tests\\unittests\\librepcb-unittests.exe
      displayName: Run LibrePCB Unittests
    - script: uv --directory ./tests/cli run --no-dev pytest -vvv --librepcb-executable="../../build/install/bin/librepcb-cli.exe"
      displayName: Run LibrePCB-CLI Functional Tests
    # GUI tests currently don't work for an unknown reason, thus disabled :-(
    # - script: uv --directory ./tests/funq run --no-dev pytest -vvv --librepcb-executable="../../build/install/bin/librepcb.exe" --reruns 5 --reruns-delay 10
    #   displayName: Run LibrePCB Functional Tests
    - bash: ./ci/upload_artifacts.sh
      displayName: Upload Artifacts
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      env:
        UPLOAD_URL: $(ARTIFACTS_UPLOAD_URL)
        UPLOAD_USER: $(ARTIFACTS_UPLOAD_USER)
        UPLOAD_PASS: $(ARTIFACTS_UPLOAD_PASS)
        UPLOAD_SIGN_KEY: $(ARTIFACTS_UPLOAD_SIGN_KEY)
