jobs:
- job: Stylecheck
  pool:
    vmImage: 'ubuntu-20.04'
  container: librepcb/librepcb-dev:ubuntu-20.04-5
  steps:
  - bash: ./ci/print_environment.sh
    displayName: Print Environment
  - bash: ./ci/stylecheck.sh
    displayName: Run Stylecheck
