jobs:
- job: Stylecheck
  pool:
    vmImage: 'ubuntu-22.04'
  container: librepcb/librepcb-dev:devtools-5
  steps:
  - bash: ./ci/print_environment.sh
    displayName: Print Environment
  - bash: ./ci/stylecheck.sh
    displayName: Run Stylecheck
  - bash: |
      git submodule update --init i18n
      python3 ./dev/i18n.py --update --translate
    displayName: Run dev/i18n.py
