jobs:
- job: Stylecheck
  pool:
    vmImage: 'ubuntu-22.04'
  container: librepcb/librepcb-dev:devtools-4
  steps:
  - bash: ./ci/print_environment.sh
    displayName: Print Environment
  - bash: ./ci/stylecheck.sh
    displayName: Run Stylecheck
