jobs:
- job: Stylecheck_Doxygen
  pool:
    vmImage: 'ubuntu-22.04'
  container: librepcb/librepcb-dev:devtools-6
  steps:
  - checkout: self
    clean: true
    submodules: recursive
  - bash: ./ci/print_environment.sh
    displayName: Print Environment
  - bash: ./ci/stylecheck.sh
    displayName: Run Stylecheck
  - bash: python3 ./dev/i18n.py --update --translate
    displayName: Build translations
  - bash: python3 ./dev/generate_editorcommandset.py --check
    displayName: Check EditorCommandSet
  - bash: python3 ./dev/find_unused_code.py
    displayName: Find unused code
  - bash: ./ci/build_doxygen.sh
    displayName: Build Doxygen Documentation
  - bash: ./ci/upload_artifacts.sh
    displayName: Upload Artifacts
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    env:
      UPLOAD_URL: $(ARTIFACTS_UPLOAD_URL)
      UPLOAD_USER: $(ARTIFACTS_UPLOAD_USER)
      UPLOAD_PASS: $(ARTIFACTS_UPLOAD_PASS)
      UPLOAD_SIGN_KEY: $(ARTIFACTS_UPLOAD_SIGN_KEY)
