import { WireMode, WindowSectionData, SchematicTabData } from "../../api/types.slint";
import { Data } from "../../api/data.slint";

component WireModeButton inherits Rectangle {
    in property <image> icon;
    in property <bool> checked: false;

    callback clicked <=> ta.clicked;

    width: self.height;
    background: checked ? #202020 : (ta.has-hover ? #707070 : transparent);

    ta := TouchArea {
        Image {
            width: 100%;
            height: 100%;
            source: icon;
        }
    }
}

export component DrawWireToolBar inherits HorizontalLayout {
    in property <int> section-index;
    in-out property <WindowSectionData> section;
    property <[SchematicTabData]> tabs: section.schematic-tabs;

    spacing: 5px;
    height: 25px;

    WireModeButton {
        icon: @image-url("../../../../../../img/wire_h_v.png");
        checked: tabs[section.current-tab-index].tool-wire-mode == WireMode.h-v;

        clicked => {
            tabs[section.current-tab-index].tool-wire-mode = WireMode.h-v;
        }
    }

    WireModeButton {
        icon: @image-url("../../../../../../img/wire_v_h.png");
        checked: tabs[section.current-tab-index].tool-wire-mode == WireMode.v-h;

        clicked => {
            tabs[section.current-tab-index].tool-wire-mode = WireMode.v-h;
        }
    }

    WireModeButton {
        icon: @image-url("../../../../../../img/wire_90_45.png");
        checked: tabs[section.current-tab-index].tool-wire-mode == WireMode.deg90-45;

        clicked => {
            tabs[section.current-tab-index].tool-wire-mode = WireMode.deg90-45;
        }
    }

    WireModeButton {
        icon: @image-url("../../../../../../img/wire_45_90.png");
        checked: tabs[section.current-tab-index].tool-wire-mode == WireMode.deg45-90;

        clicked => {
            tabs[section.current-tab-index].tool-wire-mode = WireMode.deg45-90;
        }
    }

    WireModeButton {
        icon: @image-url("../../../../../../img/wire_straight.png");
        checked: tabs[section.current-tab-index].tool-wire-mode == WireMode.straight;

        clicked => {
            tabs[section.current-tab-index].tool-wire-mode = WireMode.straight;
        }
    }
}
