import { Text } from "text.slint";
import { Constants, Data } from "../api.slint";

export component CheckBox inherits Rectangle {
    in-out property <bool> checked: false;
    in property <bool> enabled: true;
    in property <bool> read-only: false;
    in property <string> text;
    in property <length> font-size: 12px;
    in property <string> status-tip;
    in property <bool> focusable: true;
    in property <color> text-color: {
        if !enabled {
            Data.theme.palette.fg-disabled
        } else if read-only {
            Data.theme.palette.fg-placeholder
        } else {
            Data.theme.palette.fg
        }
    };
    out property has-focus <=> fs.has-focus;

    preferred-width: l.preferred-width;
    preferred-height: l.preferred-height;
    max-width: text.is-empty ? l.preferred-width : l.max-width;
    forward-focus: fs;

    // Accessibility
    accessible-role: checkbox;
    accessible-description: status-tip;
    accessible-checkable: true;
    accessible-checked: checked;
    accessible-enabled: enabled;
    accessible-label: text;
    accessible-read-only: read-only;
    accessible-action-default => {
        ta.clicked();
    }

    callback toggled(checked: bool);
    toggled(state) => {
        checked = state;
    }

    fs := FocusScope {
        enabled: enabled && focusable;

        key-pressed(event) => {
            // Only consume Space, but not Return as the Return key is often
            // used to confirm a dialog or something like that.
            if enabled && (!read-only) && (event.text == Key.Space) {
                toggled(!checked);
                return accept;
            }
            reject
        }
    }

    l := HorizontalLayout {
        spacing: 5px;

        Rectangle {
            y: (parent.height - self.height) / 2;
            width: 16px;
            height: self.width;
            background: Data.theme.palette.bg3;
            border-color: has-focus ? Constants.librepcb-color : Data.theme.palette.bg-border;
            border-width: 1px;

            if checked: Image {
                width: 80%;
                height: self.width;
                colorize: text-color;
                source: @image-url("../../../font-awesome/svgs/solid/check.svg");
                image-fit: contain;
            }
        }

        if !text.is-empty: Text {
            text: text;
            wrap: word-wrap;
            vertical-alignment: center;
            font-size: font-size;
            color: text-color;
            enabled: enabled;
            accessible-role: none;
        }
    }

    ta := TouchArea {
        enabled: enabled && !read-only;

        changed has-hover => {
            if !root.status-tip.is-empty {
                if self.has-hover {
                    Data.status-tip = root.status-tip;
                } else {
                    Data.status-tip = "";
                }
            }
        }

        clicked => {
            // The click may destroy this element without calling the
            // has-hover handler anymore, so we clear the status tip
            // manually to be on the safe side.
            if !root.status-tip.is-empty {
                Data.status-tip = "";
            }
            toggled(!checked);
        }
    }
}
