import { IconButton } from "iconbutton.slint";
import { Data } from "../api.slint";

export component FilterTermEdit inherits Rectangle {
    in property <string> term;

    preferred-height: 28px;
    background: Data.theme.palette.bg3;
    border-color: Data.theme.palette.bg-border;
    border-width: 1px;
    border-radius: self.height / 2;

    callback clear-clicked <=> clear-btn.clicked;

    HorizontalLayout {
        padding-left: 10px;
        padding-right: 7px;
        spacing: 5px;

        Text {
            vertical-alignment: center;
            color: Data.theme.palette.fg-disabled;
            font-size: 13px;
            text: @tr("Filter:");
        }

        Text {
            vertical-alignment: center;
            color: Data.theme.palette.fg;
            font-size: 13px;
            text: term;
        }

        Rectangle { }

        clear-btn := IconButton {
            y: (parent.height - self.height) / 2;
            width: self.height;
            height: min(16px, parent.height);
            style: hyperlink;
            icon: @image-url("../../../font-awesome/svgs/solid/xmark.svg");
            color-enabled: Data.theme.palette.fg-placeholder;
            accessible-label: "clear filter term";
        }
    }
}
