import { LinkText } from "linktext.slint";
import { Constants, Data } from "../api.slint";

export struct NavBarItemData {
    title: string,
    disabled: bool,
}

export component NavBar inherits HorizontalLayout {
    in property <[NavBarItemData]> items;
    in-out property <int> current-index: 0;

    callback page-clicked(index: int);
    page-clicked(index) => {
        current-index = index;
    }

    height: self.preferred-height;
    alignment: start;

    for item[index] in items: item-l := HorizontalLayout {
        item-btn := LinkText {
            width: self.preferred-width + 16px;
            height: self.preferred-height + 16px;
            vertical-alignment: center;
            horizontal-alignment: center;
            text: item.title;
            text-color: (index == current-index) ? Data.theme.palette.fg : Data.theme.palette.fg-placeholder;
            text-color-hovered: (index == current-index) ? Data.theme.palette.fg-hovered : Data.theme.palette.fg-placeholder;
            enabled: !item.disabled;

            clicked => {
                page-clicked(index);
            }

            if index == current-index: Rectangle {
                x: (parent.width - parent.preferred-width) / 2;
                y: parent.height - (parent.height - parent.preferred-height) / 2 - 2px;
                width: parent.preferred-width;
                height: 1px;
                background: Constants.librepcb-color;
            }
        }

        if (index + 1) < items.length: Text {
            text: "•";
            color: Data.theme.palette.fg-disabled;
            vertical-alignment: center;
            accessible-role: none;
        }
    }
}
