import { Data } from "../api.slint";

//TODO

export component ScrollBar inherits Rectangle {
    in property <bool> enabled;
    out property <bool> has-hover: touch-area.has-hover;
    in-out property <bool> horizontal;
    in-out property <length> maximum;
    in-out property <length> page-size;
    in-out property <length> value;
    in property <ScrollBarPolicy> policy: ScrollBarPolicy.as-needed;

    callback scrolled();

    private property <length> track-size: root.horizontal ? root.width - 2 * root.offset : root.height - 2 * offset;
    private property <length> step-size: 10px;
    private property <length> offset: 2px;

    opacity: 0.7;
    visible: (self.policy == ScrollBarPolicy.always-on) || (self.policy == ScrollBarPolicy.as-needed && self.maximum > 0);
    background: has-hover ? Data.theme.palette.control-hovered : transparent;

    thumb := Rectangle {
        width: !root.horizontal ? parent.width - 2px : root.maximum <= 0phx ? 0phx : max(min(32px, root.width), root.track-size * root.page-size / (root.maximum + root.page-size));
        height: root.horizontal ? parent.height - 2px : root.maximum <= 0phx ? 0phx : max(min(32px, root.height), root.track-size * (root.page-size / (root.maximum + root.page-size)));
        x: !root.horizontal ? (parent.width - self.width) / 2 : root.offset + (root.track-size - thumb.width) * (-root.value / root.maximum);
        y: root.horizontal ? (parent.height - self.height) / 2 : root.offset + (root.track-size - thumb.height) * (-root.value / root.maximum);
        background: {
            if touch-area.pressed {
                Data.theme.palette.control-text.mix(Data.theme.palette.control-text-muted, 0.5)
            } else if touch-area.has-hover {
                Data.theme.palette.control-text-muted
            } else {
                Data.theme.palette.control-text-disabled
            }
        };
        border-radius: min(self.width, self.height) / 2;
    }

    touch-area := TouchArea {
        property <{pressed-value: length, maximum: length, x:length, y: length}> saved-values;

        x: root.horizontal ? 0 : parent.width - self.width + 4px;
        y: (!root.horizontal) ? 0 : parent.height - self.height + 4px;
        width: (!root.horizontal) ? parent.width + 4px : parent.width;
        height: root.horizontal ? parent.height + 4px : parent.height;

        function update-saved-values() {
            self.saved-values = { pressed-value: -root.value, maximum: root.maximum, x: self.mouse-x, y: self.mouse-y };
        }

        pointer-event(event) => {
            if (event.button == PointerEventButton.left && event.kind == PointerEventKind.down) {
                self.update-saved-values();
            }
        }

        moved => {
            if (self.enabled && self.pressed) {
                // Update reference points when the size of the viewport changes to
                // avoid 'jumping' during scrolling.
                // This happens when height estimate of a ListView changes after
                // new items are loaded.
                if (self.saved-values.maximum != root.maximum) {
                    self.update-saved-values();
                }
                root.value = -max(0px, min(root.maximum, self.saved-values.pressed-value + (root.horizontal ? (self.mouse-x - self.saved-values.x) * (root.maximum / (root.track-size - thumb.width)) : (self.mouse-y - self.saved-values.y) * (root.maximum / (root.track-size - thumb.height)))));
                root.scrolled();
            }
        }

        scroll-event(event) => {
            if (root.horizontal && event.delta-x != 0) {
                root.value = max(-root.maximum, min(0px, root.value + event.delta-x));
                return accept;
            } else if (!root.horizontal && event.delta-y != 0) {
                root.value = max(-root.maximum, min(0px, root.value + event.delta-y));
                return accept;
            }
            reject
        }
    }
}

export component ScrollView {
    out property <length> visible-width <=> flickable.width;
    out property <length> visible-height <=> flickable.height;
    in-out property <length> viewport-width <=> flickable.viewport-width;
    in-out property <length> viewport-height <=> flickable.viewport-height;
    in-out property <length> viewport-x <=> flickable.viewport-x;
    in-out property <length> viewport-y <=> flickable.viewport-y;
    in property <ScrollBarPolicy> vertical-scrollbar-policy <=> vertical-bar.policy;
    in property <ScrollBarPolicy> horizontal-scrollbar-policy <=> horizontal-bar.policy;
    in property <bool> mouse-drag-pan-enabled <=> flickable.interactive;

    // FIXME: remove. This property is currently set by the ListView and is used by the native style to draw the scrollbar differently when it has focus
    in-out property <bool> has-focus;

    callback scrolled <=> flickable.flicked;

    min-height: 50px;
    min-width: 50px;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    preferred-height: 100%;
    preferred-width: 100%;

    ta := TouchArea {
        width: 100%;
        height: 100%;

        flickable := Flickable {
            interactive: false;
            viewport-y <=> vertical-bar.value;
            viewport-x <=> horizontal-bar.value;
            width: 100%;
            height: 100%;

            @children
        }

        vertical-bar := ScrollBar {
            x: parent.width - self.width;
            y: 0;
            width: self.has-hover ? 8px : 6px;
            height: horizontal-bar.visible ? parent.height - horizontal-bar.height : parent.height;
            horizontal: false;
            maximum: flickable.viewport-height - flickable.height;
            page-size: flickable.height;
            opacity: (ta.has-hover || self.has-hover) ? 0.7 : 0;

            animate width {
                delay: 50ms;
                duration: 30ms;
            }

            animate opacity {
                delay: 100ms;
                duration: 100ms;
            }

            scrolled => {
                root.scrolled()
            }
        }

        horizontal-bar := ScrollBar {
            width: vertical-bar.visible ? parent.width - vertical-bar.width : parent.width;
            height: 6px;
            y: parent.height - self.height;
            x: 0;
            horizontal: true;
            maximum: flickable.viewport-width - flickable.width;
            page-size: flickable.width;
            opacity: (ta.has-hover || self.has-hover) ? 0.7 : 0;

            animate opacity {
                delay: 100ms;
                duration: 100ms;
            }

            scrolled => {
                root.scrolled()
            }
        }
    }
}
