import { Data } from "../api.slint";

export component TextInput inherits TextInput {
    color: {
        if !self.enabled {
            Data.theme.palette.control-text-disabled
        } else if self.read-only {
            Data.theme.palette.control-text-muted
        } else {
            Data.theme.palette.control-text
        }
    };
    selection-background-color: Data.theme.palette.selection;
    selection-foreground-color: Data.theme.palette.selection-text;
}
