import { Constants, Data } from "../api.slint";

export component ToolBarWidget inherits FocusScope {
    in property <length> content-padding-left: 5px;
    in property <length> content-padding-right: 5px;
    in property <length> content-padding-top: 5px;
    in property <length> content-padding-bottom: 5px;
    in property <length> spacing: 3px;

    width: self.preferred-width;
    preferred-height: 25px;

    Rectangle {
        background: Data.theme.palette.bg3;
        border-color: {
            if root.has-focus {
                Constants.librepcb-color
            } else if root.enabled {
                Data.theme.palette.bg-border
            } else {
                transparent
            }
        }
        border-width: 1px;

        HorizontalLayout {
            padding-left: content-padding-left;
            padding-right: content-padding-right;
            padding-top: content-padding-top;
            padding-bottom: content-padding-bottom;
            spacing: spacing;

            @children
        }
    }
}
