import { Data } from "../api.slint";

export component ToolBar inherits Rectangle {
    height: 34px;
    background: Data.theme.palette.bg2;
    border-color: Data.theme.palette.bg-border;
    border-width: 1px;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: self.border-bottom-left-radius;

    HorizontalLayout {
        alignment: center;
        padding: 3px;

        @children
    }
}
