name: CI
on: [push, pull_request]
jobs:
  macos-arm64:
    name: MacOS ARM64
    runs-on: macos-14
    env:
      OS: 'mac'
      ARCH: 'arm64'
      COPYFILE_DISABLE: 1 # Stop creating shit files (https://superuser.com/questions/259703/get-mac-tar-to-stop-putting-filenames-in-tar-archives)
      HOMEBREW_NO_INSTALL_CLEANUP: 1 # Might speed up homebrew commands(?)
    steps:
      - uses: actions/checkout@v4
      - name: Print Environment
        run: ./ci/print_environment.sh
      - name: Install Dependencies
        run: source ./ci/install_dependencies.sh
      - name: Print New Environment
        run: ./ci/print_environment.sh
      - name: Build LibrePCB
        run: ./ci/build_librepcb.sh
