name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    secrets: inherit

  windows:
    name: Windows
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  macos:
    name: MacOS
    uses: ./.github/workflows/macos.yml
    secrets: inherit
