name: CI

on: [push, pull_request]

env:
  CI_BRANCH_NAME: ${{ github.ref }}
  # Specify build author as an environment variable because on Apple Silicon
  # build_librepcb.sh is run locally where we want to use a different author.
  LIBREPCB_BUILD_AUTHOR: "LibrePCB CI"
  # Configure ccache.
  CCACHE_MAXSIZE: 1G
  # Incremental builds make no sense on CI -> disable it to avoid creating
  # additional build artifacts.
  CARGO_INCREMENTAL: 0

jobs:
  windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  macos:
    uses: ./.github/workflows/macos.yml
    secrets: inherit
