name: CI

on: [push, pull_request]

env:
  CI_BRANCH_NAME: ${{ github.ref }}
  # Specify build author as an environment variable because on Apple Silicon
  # build_librepcb.sh is run locally where we want to use a different author.
  LIBREPCB_BUILD_AUTHOR: "LibrePCB CI"
  # Configure ccache.
  CCACHE_MAXSIZE: 1G
  # Incremental builds make no sense on CI -> disable it to avoid creating
  # additional build artifacts.
  CARGO_INCREMENTAL: 0

jobs:
  Ubuntu_2004_Qt_6_6_GCC:
    uses: ./.github/workflows/linux.yml
    with:
      image: librepcb/librepcb-dev:ubuntu-20.04-qt6.6-4
      deploy: true
    secrets: inherit

  windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit

  macos:
    uses: ./.github/workflows/macos.yml
    secrets: inherit
