import "../../../share/librepcb/fonts/NotoSans-Light.ttf";
import "../../../share/librepcb/fonts/NotoSans-LightItalic.ttf";
import "../../../share/librepcb/fonts/NotoSans-Regular.ttf";
import "../../../share/librepcb/fonts/NotoSans-Italic.ttf";
import "../../../share/librepcb/fonts/NotoSans-Bold.ttf";
import "../../../share/librepcb/fonts/NotoSans-BoldItalic.ttf";
import "../../../share/librepcb/fonts/NotoSansMono-Regular.ttf";

import {
    Button,
    CopyToClipboardIconButton,
    IconButton,
    LineEdit,
    ListScrollView,
    ToolTip,
} from "widgets.slint";
import { Data } from "api.slint";

export struct RenumberComponentsItemData {
    name: string,
    new-name: string,
    value: string,
}

export component RenumberComponentsDialog inherits Window {
    title: @tr("Renumber Components");
    icon: @image-url("../../../img/app/librepcb.svg");
    background: Data.theme.window;
    default-font-family: "Noto Sans";
    preferred-width: 400px;
    preferred-height: 500px;
    forward-focus: fs;

    in-out property <[RenumberComponentsItemData]> model: [
        {
            name: "U1",
            new-name: "U5",
            value: "NE555",
        },
        {
            name: "U2",
            new-name: "U1",
            value: "STM32F407VET6",
        },
        {
            name: "R3",
            new-name: "R27",
            value: "100k",
        },
        {
            name: "R12",
            new-name: "R13",
            value: "1k",
        },
    ];
    in-out property <int> current-index: 0;
    property <RenumberComponentsItemData> current-item: model[current-index];
    property <length> item-height: 24px;

    callback apply-requested();
    callback close-requested();

    function set-current-index(index: int) {
        if ((index + 1) * item-height) > (view.height - view.content-y) {
            view.content-y = -(index + 1) * item-height + view.height;
        } else if (index * item-height) < -(view.content-y) {
            view.content-y = -(index * item-height);
        }
        current-index = index;
    }

    VerticalLayout {
        padding: 7px;
        spacing: 8px;

        Text {
            text: @tr("The following components will be renamed to put them into a natural order:");
            wrap: word-wrap;
            color: Data.theme.base-text;
        }

        fs := FocusScope {
            vertical-stretch: 1;

            Rectangle {
                background: Data.theme.control;
                border-color: Data.theme.control-border;
                border-width: 1px;

                if model.length == 0: VerticalLayout {
                    width: 80%;
                    height: 80%;
                    alignment: center;
                    spacing: 8px;

                    Rectangle {
                        Image {
                            width: min(0.5 * fs.width, 150px);
                            height: min(0.5 * fs.height, 150px);
                            source: @image-url("../../font-awesome/svgs/solid/check.svg");
                            colorize: Data.theme.control-text-muted.with-alpha(0.3);
                            image-fit: contain;
                        }
                    }

                    Text {
                        text: @tr("No components to renumber");
                        font-size: 18px;
                        horizontal-alignment: center;
                        color: Data.theme.control-text-muted.with-alpha(0.7);
                        wrap: word-wrap;
                    }
                }

                view := ListScrollView {
                    width: parent.width - 2px;
                    height: parent.height - 2px;
                    accessible-item-count: model.length;

                    GridLayout {
                        for item[index] in model: Row {
                            Rectangle {
                                ta-1 := TouchArea {
                                    clicked => {
                                        if current-index != index {
                                            set-current-index(index);
                                        }
                                        fs.focus();
                                    }
                                }

                                background: {
                                    if index == current-index {
                                        Data.theme.control-checked
                                    } else if ta-1.has-hover || ta-2.has-hover {
                                        Data.theme.control-hovered
                                    } else {
                                        Data.theme.control
                                    }
                                };

                                HorizontalLayout {
                                    spacing: 7px;
                                    padding-top: 1px;
                                    padding-bottom: 1px;
                                    padding-left: 4px;
                                    padding-right: 4px;

                                    Text {
                                        vertical-alignment: center;
                                        color: Data.theme.control-text;
                                        text: item.name + " → " + item.new-name;
                                        accessible-role: none;
                                    }
                                }
                            }

                            Rectangle {
                                horizontal-stretch: 1;

                                ta-2 := TouchArea {
                                    clicked => {
                                        if current-index != index {
                                            set-current-index(index);
                                        }
                                        fs.focus();
                                    }
                                }

                                background: {
                                    if index == current-index {
                                        Data.theme.control-checked
                                    } else if ta-1.has-hover || ta-2.has-hover {
                                        Data.theme.control-hovered
                                    } else {
                                        Data.theme.control
                                    }
                                };

                                HorizontalLayout {
                                    spacing: 7px;
                                    padding-top: 1px;
                                    padding-bottom: 1px;
                                    padding-left: 4px;
                                    padding-right: 4px;

                                    Text {
                                        vertical-alignment: center;
                                        color: Data.theme.control-text;
                                        text: item.value;
                                        accessible-role: none;
                                    }
                                }
                            }
                        }
                    }
                }
            }

            key-pressed(event) => {
                if event.text == Key.DownArrow {
                    set-current-index(min(current-index + 1, model.length - 1));
                    return accept;
                } else if event.text == Key.UpArrow {
                    set-current-index(max(current-index - 1, 0));
                    return accept;
                }
                reject
            }
        }

        HorizontalLayout {
            spacing: 5px;

            if model.length > 0: apply-btn := Button {
                horizontal-stretch: 5;
                text: @tr("Apply");
                primary: true;

                clicked => {
                    apply-requested();
                }
            }

            close-btn := Button {
                horizontal-stretch: 1;
                text: @tr("Close");

                clicked => {
                    close-requested();
                }
            }
        }
    }
}
